
import { DATA } from './data.js';

const DB_NAME='pico-tamachibi-pwa'; const DB_VERSION=3;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)); const rand=n=>Math.floor(Math.random()*n);
const pick=a=>a[rand(a.length)]; const now=()=>Date.now();
const fmtTime=d=>new Intl.DateTimeFormat([], {hour:'numeric',minute:'2-digit'}).format(d);
const fmtDay=d=>new Intl.DateTimeFormat([], {weekday:'short'}).format(d);
let db,state,view='tama',roomIndex=0,cityIndex=0,deferredInstall=null,saveTimer=null,renderFrame=0;
let dialogueResolver=null, currentTrackIndex=-1, tracks=[], objectUrl=null, gameSession=null;
const audio=$('#audio'), canvas=$('#gameCanvas'), ctx=canvas.getContext('2d'); ctx.imageSmoothingEnabled=false;
const dcanvas=$('#dialogueCanvas'), dctx=dcanvas.getContext('2d'); dctx.imageSmoothingEnabled=false;

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('kv'))d.createObjectStore('kv');if(!d.objectStoreNames.contains('tracks'))d.createObjectStore('tracks',{keyPath:'id',autoIncrement:true});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function idbGet(store,key){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function idbPut(store,val,key){return new Promise((res,rej)=>{const s=db.transaction(store,'readwrite').objectStore(store);const r=key===undefined?s.put(val):s.put(val,key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function idbDelete(store,key){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function idbAll(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}

function newState(){const t=now(); return {
 version:1,savedAt:t,lastTick:t,createdAt:t,view:'tama',roomIndex:0,cityIndex:0,settings:{notifications:false,sound:true,reducedMotion:false,difficulty:'normal',careAlerts:true},
 pet:{name:'Mochi',species:rand(50),stage:'baby',bornAt:t,ageMinutes:0,generation:1,needs:{food:82,fun:82,energy:85,clean:90,health:100},poop:0,sick:false,emotion:'curious',bond:55,trust:50,discipline:25,intelligence:20,kindness:35,fitness:25,coins:250,careMisses:0,schoolXP:0,career:null,careerXP:0,spouse:null,children:[],companion:null,asleep:false,lastConversation:0,lastEventDay:-1},
 inventory:{food:6,snacks:3,medicine:2,seeds:4,materials:0,hats:['Tiny Crown'],rooms:['Cozy Cottage']},
 garden:{plots:Array.from({length:4},()=>null),indoor:Array.from({length:4},()=>null)},
 aquarium:{clean:85,quality:85,fish:[]},
 relationships:Object.fromEntries(DATA.neighbors.map(n=>[n,{bond:0,met:false}])),
 collections:{species:[0],fish:[],plants:[],achievements:[],museum:[]},
 narrative:{openness:50,confidence:45,empathy:45,honesty:50,resilience:45,responsibility:40,independence:30,security:55,promises:[],keepsakes:[],traditions:[],memories:[],activeArc:null,history:[]},
 goals:{daily:[],weekly:[],lastDay:''},notifications:{lastShown:0,log:[]},music:{favorites:[],recent:[],volume:.72,shuffle:false},summary:[]
};}
async function loadState(){state=await idbGet('kv','state')||newState(); view=state.view||'tama'; roomIndex=state.roomIndex||0;cityIndex=state.cityIndex||0; normalizeState();}
function normalizeState(){state.pet.needs ||= {food:80,fun:80,energy:80,clean:90,health:100};state.music ||= {favorites:[],recent:[],volume:.72,shuffle:false};state.notifications ||= {lastShown:0,log:[]};state.narrative ||= newState().narrative;state.settings ||= newState().settings;}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveState,250);}
async function saveState(){if(!state)return;state.savedAt=now();state.view=view;state.roomIndex=roomIndex;state.cityIndex=cityIndex;await idbPut('kv',structuredClone(state),'state');}

function stageFromAge(min){const days=min/1440;if(days<1)return'baby';if(days<3)return'child';if(days<6)return'teen';if(days<20)return'adult';return'elder';}
function scheduleFor(stage){return {baby:{bed:19,wake:7},child:{bed:20,wake:7,school:[8,15]},teen:{bed:22,wake:7,school:[8,15]},adult:{bed:23,wake:6,work:[9,17]},elder:{bed:21,wake:6}}[stage]||{bed:20,wake:7};}
function currentActivity(date=new Date()){const p=state.pet,s=scheduleFor(p.stage),h=date.getHours()+date.getMinutes()/60,weekend=[0,6].includes(date.getDay());const asleep=s.bed>s.wake?(h>=s.bed||h<s.wake):(h>=s.bed&&h<s.wake);if(asleep)return'sleep';if(!weekend&&s.school&&h>=s.school[0]&&h<s.school[1])return'school';if(!weekend&&s.work&&p.career&&h>=s.work[0]&&h<s.work[1])return'work';return'home';}
function difficultyRate(){return {relaxed:.65,normal:1,challenge:1.3,sandbox:.2}[state.settings.difficulty]||1;}
function advanceMinutes(minutes,offline=false){if(minutes<=0)return;minutes=Math.min(minutes,60*24*30);const p=state.pet;const oldStage=p.stage;p.ageMinutes+=minutes;p.stage=stageFromAge(p.ageMinutes);if(oldStage!==p.stage){state.collections.species.push(p.species);addMemory(`Evolved into ${p.stage} stage.`);toast(`${p.name} became a ${p.stage}!`);}
 let remaining=minutes;let cursor=new Date(now()-minutes*60000);const rate=difficultyRate();
 while(remaining>0){const step=Math.min(15,remaining);const act=currentActivity(cursor);p.asleep=act==='sleep';if(act==='sleep'){p.needs.energy=clamp(p.needs.energy+step*.10);p.needs.food=clamp(p.needs.food-step*.008*rate);p.needs.clean=clamp(p.needs.clean-step*.002*rate);}else if(act==='school'||act==='work'){p.needs.energy=clamp(p.needs.energy-step*.018*rate);p.needs.fun=clamp(p.needs.fun-step*.006*rate);if(act==='school'){p.schoolXP+=step/60;p.intelligence=clamp(p.intelligence+step*.003);}else{p.careerXP+=step/60;p.coins+=step/180;}}else{p.needs.food=clamp(p.needs.food-step*.024*rate);p.needs.fun=clamp(p.needs.fun-step*.014*rate);p.needs.energy=clamp(p.needs.energy-step*.017*rate);p.needs.clean=clamp(p.needs.clean-step*.009*rate);if(Math.random()<step/1800&&p.needs.food>20)p.poop=Math.min(3,p.poop+1);} cursor=new Date(cursor.getTime()+step*60000);remaining-=step;}
 if(p.poop)p.needs.clean=clamp(p.needs.clean-p.poop*minutes*.002);const critical=Object.values(p.needs).filter(v=>v<12).length;if(critical||p.poop>=2){p.needs.health=clamp(p.needs.health-minutes*.005*(critical+p.poop*.3));}if(p.needs.health<28&&Math.random()<minutes/6000)p.sick=true;
 updateGarden(minutes);updateAquarium(minutes);checkGoals();maybeDailyEvent();if(offline){state.summary.unshift(`While away for ${prettyDuration(minutes)}, ${p.name} was ${currentActivity(new Date())}.`);state.summary=state.summary.slice(0,12);} }
function updateGarden(minutes){for(const plot of [...state.garden.plots,...state.garden.indoor])if(plot){plot.growth=clamp(plot.growth+minutes*(plot.water>15?0.006:0.002),0,100);plot.water=clamp(plot.water-minutes*.008);if(plot.water<10)plot.health=clamp(plot.health-minutes*.004);}}
function updateAquarium(minutes){state.aquarium.clean=clamp(state.aquarium.clean-minutes*.004*state.aquarium.fish.length);state.aquarium.quality=clamp(state.aquarium.quality-minutes*.003*state.aquarium.fish.length);for(const f of state.aquarium.fish){f.hunger=clamp(f.hunger-minutes*.006);f.mood=clamp(f.mood+(state.aquarium.clean>50?minutes*.001:-minutes*.004));}}
function applyOffline(){const elapsed=Math.floor((now()-(state.savedAt||now()))/60000);if(elapsed>0)advanceMinutes(elapsed,true);state.lastTick=now();}
function tick(){const elapsed=Math.floor((now()-state.lastTick)/60000);if(elapsed>0){advanceMinutes(elapsed);state.lastTick+=elapsed*60000;queueSave();checkCareNotification();}render();}

function addMemory(text){state.narrative.memories.unshift({text,at:now()});state.narrative.memories=state.narrative.memories.slice(0,80);}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2300);}
function prettyDuration(min){if(min<60)return`${min} minutes`;const h=Math.floor(min/60),m=min%60;if(h<24)return`${h}h ${m}m`;return`${Math.floor(h/24)}d ${h%24}h`;}

function drawSprite(c,id,x,y,scale=1,color='#f7f4e8'){const rows=DATA.sprites[id%50];c.fillStyle=color;for(let r=0;r<32;r++){const bits=rows[r]>>>0;for(let col=0;col<32;col++)if((bits & (0x80000000>>>col))!==0)c.fillRect(x+col*scale,y+r*scale,scale,scale);}}
function clearCanvas(){ctx.fillStyle='#05060b';ctx.fillRect(0,0,128,64);}
function drawWindow(x,y,night=false){ctx.strokeStyle='#7ce7b7';ctx.lineWidth=1;ctx.strokeRect(x,y,22,15);ctx.beginPath();ctx.moveTo(x+11,y);ctx.lineTo(x+11,y+15);ctx.moveTo(x,y+8);ctx.lineTo(x+22,y+8);ctx.stroke();ctx.fillStyle='#f7f4e8';if(night){ctx.fillRect(x+4,y+3,2,2);ctx.fillRect(x+16,y+4,1,1);}else{ctx.beginPath();ctx.arc(x+5,y+4,3,0,Math.PI*2);ctx.fill();}}
function drawRoom(theme='pet'){clearCanvas();ctx.strokeStyle='#7ce7b7';ctx.fillStyle='#7ce7b7';ctx.fillRect(0,0,128,3);ctx.fillRect(0,3,3,58);ctx.fillRect(125,3,3,58);ctx.fillRect(0,59,128,5);drawWindow(101,10,currentActivity()==='sleep');ctx.strokeStyle='#f7f4e8';if(theme==='kitchen'){ctx.strokeRect(6,32,31,23);ctx.strokeRect(91,32,29,23);ctx.fillRect(10,36,10,2);ctx.strokeRect(98,38,15,11);}else if(theme==='garden'){for(let i=0;i<4;i++){ctx.strokeRect(7+i*30,39,24,15);const p=state.garden.plots[i];if(p)drawPlant(12+i*30,50,p.growth,p.health);}ctx.fillRect(0,55,128,2);}else if(theme==='aquarium'){ctx.strokeRect(7,22,114,32);ctx.fillRect(8,49,112,2);for(let i=0;i<state.aquarium.fish.length;i++)drawFish(18+i*17,30+(i%2)*10,i);}else{ctx.strokeRect(7,39,30,15);ctx.strokeRect(94,35,26,19);ctx.strokeRect(8,15,18,12);ctx.fillRect(41,53,47,2);} }
function drawPlant(x,y,growth=40,health=80){ctx.strokeStyle=health<30?'#ff6b7a':'#f7f4e8';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-8-growth/10);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(x-4,y-8-growth/10,4,2);ctx.fillRect(x+1,y-12-growth/12,4,2);}
function drawFish(x,y,i){ctx.fillStyle='#f7f4e8';ctx.beginPath();ctx.ellipse(x,y,6,3,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(x-6,y);ctx.lineTo(x-10,y-4);ctx.lineTo(x-10,y+4);ctx.closePath();ctx.fill();ctx.fillStyle='#05060b';ctx.fillRect(x+3,y-1,1,1);}
function drawCity(place){clearCanvas();ctx.strokeStyle='#7ce7b7';ctx.fillStyle='#7ce7b7';for(let i=0;i<4;i++){const h=20+((i*9+cityIndex*5)%24);const x=3+i*31;ctx.strokeRect(x,58-h,27,h);for(let wy=42;wy>58-h+4;wy-=7)for(let wx=x+5;wx<x+24;wx+=8)ctx.fillRect(wx,wy,2,3);}ctx.fillRect(0,58,128,2);ctx.fillStyle='#f7f4e8';ctx.font='6px monospace';ctx.fillText(place.toUpperCase().slice(0,18),5,8);}
function drawMusic(){drawRoom('pet');drawSprite(ctx,state.pet.species,48,22,1);ctx.strokeStyle='#ffc857';ctx.beginPath();ctx.arc(64,34,19,Math.PI,Math.PI*2);ctx.stroke();ctx.strokeRect(44,35,4,9);ctx.strokeRect(80,35,4,9);ctx.fillStyle='#ffc857';for(let i=0;i<3;i++){const x=91+i*10,y=16+((renderFrame+i*7)%15);ctx.fillRect(x,y,2,9);ctx.fillRect(x-3,y+7,5,3);} }
function drawScene(){renderFrame++;const act=currentActivity();if(currentTrackIndex>=0&&!audio.paused){drawMusic();return;}if(view==='city'){drawCity(DATA.city[cityIndex]);return;}const room=view==='home'?DATA.rooms[roomIndex]:'Pet Room';drawRoom(room==='Kitchen'?'kitchen':room==='Garden'||room==='Plant Room'?'garden':room==='Aquarium'?'aquarium':'pet');if(act==='school'||act==='work'){ctx.fillStyle='#05060b';ctx.fillRect(34,17,60,31);ctx.strokeStyle='#7ce7b7';ctx.strokeRect(34,17,60,31);ctx.fillStyle='#f7f4e8';ctx.font='7px monospace';ctx.fillText(act==='school'?'AT SCHOOL':'AT WORK',43,30);ctx.fillText('CARE COVERED',40,41);return;}if(act==='sleep'){drawSprite(ctx,state.pet.species,48,25,1,'#aeb8c8');ctx.fillStyle='#7fb8ff';ctx.font='9px monospace';ctx.fillText('Z',87,24);ctx.font='7px monospace';ctx.fillText('z',96,18);return;}drawSprite(ctx,state.pet.species,48+Math.round(Math.sin(renderFrame/10)*2),22,1);if(state.pet.spouse)drawSprite(ctx,state.pet.spouse.species,88,31,.5);if(state.pet.companion){ctx.fillStyle='#ffc857';ctx.beginPath();ctx.arc(35,48,5,0,Math.PI*2);ctx.fill();}if(state.pet.poop){ctx.fillStyle='#f7f4e8';for(let i=0;i<state.pet.poop;i++){ctx.fillRect(12+i*12,51,8,4);ctx.fillRect(14+i*12,48,5,3);}}}

function needInfo(){const n=state.pet.needs;return [['Food',n.food,'🍙'],['Fun',n.fun,'♥'],['Energy',n.energy,'Z'],['Clean',n.clean,'✦'],['Health',n.health,'+'],['Bond',state.pet.bond,'∞']];}
function renderStatus(){const activity=currentActivity();const strip=$('#statusStrip');if(['school','work','sleep'].includes(activity)){const s=scheduleFor(state.pet.stage);strip.innerHTML=`<div class="activity-status"><div><b>${activity==='sleep'?'Sleeping':activity==='school'?'At school':'At work'}</b><small> · ${activity==='sleep'?'Energy recovering':'Needs are covered'}</small></div><span>${activity==='sleep'?`Wake ${formatHour(s.wake)}`:activity==='school'?'Back 3:00 PM':'Back 5:00 PM'}</span></div>`;return;}strip.innerHTML=needInfo().map(([label,val,icon])=>{const cls=val<15?'critical blink fast':val<35?'warn blink':'';return`<div class="need ${cls}"><div class="need-row"><span>${icon} ${label}</span><span>${Math.round(val)}</span></div><div class="meter"><i style="width:${clamp(val)}%"></i></div></div>`}).join('');}
function formatHour(h){const d=new Date();d.setHours(h,0,0,0);return fmtTime(d);}
function sceneInfo(){if(view==='tama')return['Pet Room',currentActivity()==='home'?'Together at home':currentActivity().toUpperCase()];if(view==='home')return[DATA.rooms[roomIndex],roomSubtitle(DATA.rooms[roomIndex])];return[DATA.city[cityIndex],citySubtitle(DATA.city[cityIndex])];}
function roomSubtitle(r){return({Kitchen:'Cook meals and recipes',Garden:'Grow crops and harvest',Aquarium:'Care for fish', 'Plant Room':'Raise indoor plants','Family Room':'Spouse, children, and legacy','Pet Room':'Decorate and relax'})[r]||'';}
function citySubtitle(p){return({'School / Work':'Study, careers, and schedule',Market:'Buy food, seeds, and items',Cafe:'Socialize and relax',Park:'Friends, clubs, and exercise',Neighbors:'Relationships and family',Clinic:'Health and treatment',Museum:'Collections and legacy',Spaceport:'Expeditions and discoveries'})[p]||'';}
function render(){if(!state)return;$('#petName').textContent=state.pet.name;$('#stageChip').textContent=state.pet.stage.toUpperCase();$('#clock').textContent=fmtTime(new Date());$('#activityLabel').textContent=`${fmtDay(new Date())} · ${currentActivity().toUpperCase()}`;$$('.view-switch button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const [title,sub]=sceneInfo();$('#sceneTitle').textContent=title;$('#sceneSubtitle').textContent=sub;$('#sceneBadge').textContent=currentTrackIndex>=0&&!audio.paused?'♫ MUSIC':view.toUpperCase();renderStatus();drawScene();renderQuickActions();}
function renderQuickActions(){let acts=[];if(view==='tama')acts=[['🍙','Feed',()=>feed(false)],['🧼','Clean',cleanPet],['💬','Talk',startParentDialogue],['🎮','Play',openPlay],['💊','Health',healPet],['📊','Status',openStatus]];else if(view==='home'){const r=DATA.rooms[roomIndex];acts=r==='Garden'?[['🌱','Plant',openGarden],['💧','Water',()=>gardenAction('water')],['✂','Tend',()=>gardenAction('tend')],['🧺','Harvest',()=>gardenAction('harvest')]]:r==='Aquarium'?[['🐟','Fish',openAquarium],['🍤','Feed',()=>aquariumAction('feed')],['🫧','Clean',()=>aquariumAction('clean')],['➕','Adopt',()=>aquariumAction('adopt')]]:r==='Kitchen'?[['🍲','Cook',openKitchen],['🍙','Feed',()=>feed(false)],['🍰','Snack',()=>feed(true)],['🧹','Tidy',cleanPet]]:r==='Family Room'?[['👪','Family',openFamily],['🎁','Keepsakes',openNarrative],['📖','Legacy',openCollections],['💬','Meeting',startGrowingDialogue]]:[['🪑','Decor',openDecor],['💬','Talk',startParentDialogue],['🎮','Play',openPlay],['😴','Bedtime',openBedtime]];}else{const p=DATA.city[cityIndex];acts=p==='School / Work'?[['💼','Career',openCareer],['🎮','Practice',openStageGames],['📋','Report',openStatus],['🕒','Schedule',openStatus]]:p==='Market'?[['🛒','Shop',openShop],['🌱','Seeds',()=>shopCategory('seeds')],['🎩','Hats',()=>shopCategory('hats')],['🍱','Food',()=>shopCategory('food')]]:p==='Neighbors'?[['👋','Visit',openNeighbors],['💗','Date',openFamily],['🎁','Gift',()=>neighborAction('gift')],['🎮','Play',openPlay]]:p==='Clinic'?[['🩺','Checkup',healPet],['💊','Medicine',healPet],['📋','Health',openStatus],['🤝','Help',()=>cityReward('kind')]]:p==='Museum'?[['🏛','Museum',openCollections],['🦴','Fossils',openCollections],['🏆','Trophies',openCollections],['👪','Legacy',openFamily]]:[['🎮','Activity',openPlay],['💬','Talk',startParentDialogue],['🧭','Explore',()=>cityReward('explore')],['📌','Info',openStatus]];}$('#quickActions').innerHTML=acts.map((a,i)=>`<button data-i="${i}"><span>${a[0]}</span>${a[1]}</button>`).join('');$$('#quickActions button').forEach(b=>b.onclick=acts[+b.dataset.i][2]);}

function showModal(title,body,eyebrow='MENU'){const m=$('#modal');$('#modalTitle').textContent=title;$('#modalEyebrow').textContent=eyebrow;$('#modalBody').innerHTML=body;m.classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');if(gameSession)stopGame();}
function menu(title,items,eyebrow='MENU'){showModal(title,`<div class="menu-grid">${items.map((it,i)=>`<button class="menu-item" data-i="${i}"><span class="glyph">${it.icon||'•'}</span><span><strong>${it.label}</strong><small>${it.desc||''}</small></span></button>`).join('')}</div>`,eyebrow);$$('#modalBody [data-i]').forEach(b=>b.onclick=()=>items[+b.dataset.i].action());}
function showDialogue({type='TALK',title='',text='',choices=[],onChoice=null}){$('#dialogueType').textContent=type;$('#dialogueTitle').textContent=title;$('#dialogueText').textContent=text;$('#dialogueChoices').innerHTML=choices.map((c,i)=>`<button class="choice" data-i="${i}">${c}</button>`).join('');$('#dialogueContinue').classList.add('hidden');drawDialoguePet();$('#dialogue').classList.remove('hidden');$$('#dialogueChoices button').forEach(b=>b.onclick=()=>onChoice?.(+b.dataset.i));}
function dialogueReply(text){$('#dialogueText').textContent=text;$('#dialogueChoices').innerHTML='';const b=$('#dialogueContinue');b.classList.remove('hidden');b.onclick=closeDialogue;}
function closeDialogue(){$('#dialogue').classList.add('hidden');dialogueResolver?.();dialogueResolver=null;queueSave();render();}
function drawDialoguePet(){dctx.fillStyle='#080a12';dctx.fillRect(0,0,48,48);drawSprite(dctx,state.pet.species,8,8,1);}

function applyChange(obj){for(const [k,v] of Object.entries(obj)){if(k in state.pet.needs)state.pet.needs[k]=clamp(state.pet.needs[k]+v);else if(k in state.pet)state.pet[k]=typeof state.pet[k]==='number'?clamp(state.pet[k]+v,0,k==='coins'?999999:100):v;else if(k in state.narrative)state.narrative[k]=clamp(state.narrative[k]+v); }queueSave();render();}
function feed(snack){if(currentActivity()!=='home')return toast('Care is covered while away.');if(state.inventory[snack?'snacks':'food']<=0)return toast('None left. Visit the market.');state.inventory[snack?'snacks':'food']--;applyChange(snack?{food:10,fun:8}:{food:24,clean:-2,bond:1});addMemory(`${snack?'Shared a snack':'Had a meal'} together.`);toast(snack?'Snack time!':'Tummy filled.');}
function cleanPet(){if(currentActivity()!=='home')return toast('Care is covered while away.');state.pet.poop=0;applyChange({clean:35,bond:1});toast('All clean.');}
function healPet(){if(state.inventory.medicine>0&&state.pet.sick){state.inventory.medicine--;state.pet.sick=false;applyChange({health:35,bond:2});toast('Medicine helped.');}else{applyChange({health:8});toast('Health checked.');}}
function openBedtime(){const a=currentActivity();showModal('Bedtime',`<div class="panel"><h3>${a==='sleep'?'Sleeping now':'Next bedtime'}</h3><p>${a==='sleep'?'Night sleep is restoring energy.':`Bedtime is ${formatHour(scheduleFor(state.pet.stage).bed)}. Quick rests cannot replace scheduled sleep.`}</p></div><button class="primary" id="ritualBtn">Start bedtime ritual</button>`,'ROUTINE');$('#ritualBtn').onclick=()=>{closeModal();startGrowingDialogue('Bedtime Rituals');};}
function openKitchen(){menu('Kitchen',[{icon:'🍲',label:'Herb Soup',desc:'Food + health',action:()=>cook('Herb Soup',28,10)},{icon:'🥗',label:'Garden Plate',desc:'Food + clean',action:()=>cook('Garden Plate',24,4)},{icon:'🍓',label:'Berry Bite',desc:'Food + fun',action:()=>cook('Berry Bite',18,12)},{icon:'👑',label:'Royal Stew',desc:'Large family meal',action:()=>cook('Royal Stew',40,15)}],'COOKING');}
function cook(name,food,fun){if(state.inventory.materials<1)return toast('Harvest ingredients first.');state.inventory.materials--;applyChange({food,fun,bond:2});addMemory(`Cooked ${name}.`);closeModal();toast(name+' served.');}

function openPlay(){menu('Play',[{icon:'🕹',label:'Arcade Games',desc:`${DATA.arcadeGames.length} games`,action:openArcade},{icon:'🎒',label:'Life-stage Games',desc:`Five ${state.pet.stage} games`,action:openStageGames},{icon:'🏆',label:'Achievements',desc:`${state.collections.achievements.length} earned`,action:openCollections}], 'GAMES');}
function openArcade(){menu('Arcade Games',DATA.arcadeGames.map((g,i)=>({icon:['🧠','💣','🦘','🧱','☄','🎵','🐟','🍎','☁','🌿','🛸','🚩','🗺'][i],label:g,desc:['Memory','Sort','Timing','Catch','Timing'][i%5],action:()=>startGame(g,['memory','sort','timing','catch','dodge'][i%5],false)})),'ARCADE');}
function openStageGames(){const games=DATA.lifeStageGames[state.pet.stage]||DATA.lifeStageGames.adult;menu(`${state.pet.stage} Games`,games.map((g,i)=>({icon:['🧺','🏃','⏱','🧠','↔'][i],label:g,desc:['Catch','Dodge','Timing','Memory','Sort'][i],action:()=>startGame(g,['catch','dodge','timing','memory','sort'][i],true)})),'LIFE STAGE');}
function startGame(name,type,stageGame){showModal(name,`<div class="game-overlay"><canvas id="miniCanvas" class="mini-canvas" width="128" height="64"></canvas><div class="row"><b id="gameScore">Score 0</b><span id="gameTime">20s</span></div><div class="game-buttons"><button id="gameLeft">◀ Left</button><button id="gameAction" class="primary">● Act</button><button id="gameRight">Right ▶</button></div><button id="endGame" class="danger" style="width:100%;margin-top:.55rem">End game</button></div>`,'MINIGAME');const c=$('#miniCanvas'),g=c.getContext('2d');g.imageSmoothingEnabled=false;gameSession={name,type,stageGame,canvas:c,g,score:0,started:performance.now(),duration:20000,player:64,items:[],sequence:[],step:0,marker:0,dir:1,active:true};$('#gameLeft').ontouchstart=$('#gameLeft').onmousedown=()=>gameInput('left');$('#gameRight').ontouchstart=$('#gameRight').onmousedown=()=>gameInput('right');$('#gameAction').onclick=()=>gameInput('action');$('#endGame').onclick=stopGame;if(type==='memory')newMemoryRound();requestAnimationFrame(gameLoop);}
function gameInput(dir){const s=gameSession;if(!s)return;if(dir==='left')s.player=clamp(s.player-14,6,122);if(dir==='right')s.player=clamp(s.player+14,6,122);if(s.type==='timing'&&dir==='action'){if(s.marker>48&&s.marker<80)s.score+=2;else s.score=Math.max(0,s.score-1);s.marker=0;}if(s.type==='sort'&&(dir==='left'||dir==='right')){if((s.current%2===0&&dir==='left')||(s.current%2===1&&dir==='right'))s.score++;else s.score=Math.max(0,s.score-1);s.current=rand(10);}if(s.type==='memory'&&(dir==='left'||dir==='right')){const v=dir==='left'?0:1;if(v===s.sequence[s.step]){s.step++;if(s.step>=s.sequence.length){s.score+=s.sequence.length;newMemoryRound();}}else{s.score=Math.max(0,s.score-1);s.step=0;}}}
function newMemoryRound(){const s=gameSession;s.sequence=Array.from({length:Math.min(6,2+Math.floor(s.score/3))},()=>rand(2));s.step=0;s.showUntil=performance.now()+1200;}
function gameLoop(t){const s=gameSession;if(!s||!s.active)return;const elapsed=t-s.started,left=Math.max(0,s.duration-elapsed);$('#gameScore').textContent=`Score ${s.score}`;$('#gameTime').textContent=`${Math.ceil(left/1000)}s`;const g=s.g;g.fillStyle='#05060b';g.fillRect(0,0,128,64);g.strokeStyle='#7ce7b7';g.strokeRect(0,0,127,63);g.fillStyle='#f7f4e8';if(s.type==='catch'||s.type==='dodge'){if(Math.random()<.06)s.items.push({x:rand(120)+4,y:4,bad:s.type==='dodge'||Math.random()<.25});for(const it of s.items){it.y+=s.type==='dodge'?1.3:1;g.fillStyle=it.bad?'#ff6b7a':'#ffc857';g.fillRect(it.x-3,it.y-3,6,6);}s.items=s.items.filter(it=>{if(it.y>54&&Math.abs(it.x-s.player)<9){s.score+=it.bad?-1:1;return false;}return it.y<64;});g.fillStyle='#7ce7b7';g.fillRect(s.player-7,55,14,5);}else if(s.type==='timing'){s.marker+=s.dir*2;if(s.marker>120||s.marker<2)s.dir*=-1;g.fillStyle='#ffffff22';g.fillRect(8,28,112,8);g.fillStyle='#7ce7b7';g.fillRect(48,27,32,10);g.fillStyle='#ffc857';g.fillRect(s.marker,23,3,18);}else if(s.type==='sort'){s.current??=rand(10);g.font='20px sans-serif';g.fillText(s.current%2?'◆':'●',53,35);g.font='8px sans-serif';g.fillText('ROUND',11,56);g.fillText('POINT',87,56);}else if(s.type==='memory'){g.font='11px monospace';if(t<s.showUntil)g.fillText(s.sequence.map(v=>v?'R':'L').join(' '),25,33);else g.fillText(`Repeat ${s.step}/${s.sequence.length}`,31,33);}if(left<=0){finishGame();return;}requestAnimationFrame(gameLoop);}
function finishGame(){const s=gameSession;if(!s)return;s.active=false;const win=s.score>=5;state.pet.needs.energy=clamp(state.pet.needs.energy-(s.stageGame?5:3));state.pet.needs.fun=clamp(state.pet.needs.fun+Math.max(3,s.score*2));state.pet.bond=clamp(state.pet.bond+(win?2:1));if(win){state.pet.coins+=10+s.score;state.pet.intelligence=clamp(state.pet.intelligence+1);unlockAchievement(`Won ${s.name}`);}queueSave();showModal(s.name,`<div class="panel"><h3>${win?'Great job!':'Good practice'}</h3><p>Score: ${s.score}</p><p>${win?'You earned coins and skill progress.':'Try again to improve the skill.'}</p></div><button id="again" class="primary">Play again</button>`,'RESULT');$('#again').onclick=()=>startGame(s.name,s.type,s.stageGame);gameSession=null;}
function stopGame(){if(gameSession){gameSession.active=false;gameSession=null;}closeModalOnly();}
function closeModalOnly(){$('#modal').classList.add('hidden');}

function stageTopics(){return DATA.parentTopics.filter(t=>t.stage===state.pet.stage);}
function startParentDialogue(){const topics=stageTopics();const topic=pick(topics.length?topics:DATA.parentTopics.filter(t=>t.stage==='adult'));showDialogue({type:`${state.pet.stage.toUpperCase()} TALK`,title:topic.question,text:topic.prompt,choices:topic.choices,onChoice:i=>{const positive=i<2;applyChange(positive?{bond:2,trust:2}:{bond:-2,trust:-2});state.narrative.openness=clamp(state.narrative.openness+(positive?2:-2));state.narrative.history.unshift({topic:topic.id,choice:i,at:now()});addMemory(`${topic.prompt} You answered: ${topic.choices[i]}.`);dialogueReply(topic.replies[i]);}});}
const featureResponses={
'Story Arc':['Remember what we tried','Make a new plan','Step away for now'],'Family Values':['Explain the value','Find a fair balance','Do what is easiest'],'Rupture and Repair':['Name what hurt','Offer a real repair','Pretend it is fine'],'Promises':['Keep it today','Reschedule honestly','Forget about it'],'Bedtime Rituals':['Stay and listen','Choose a calming ritual','Keep playing instead'],'Affection and Consent':['Ask what feels okay','Offer quiet company','Ignore the boundary'],'School Reports':['Praise effort','Practice together','Compare to others'],'Chores':['Do it together','Set a fair plan','Shame the mistake'],'Secrets and Privacy':['Ask gently','Check safety only','Read it secretly'],'Meaningful Apology':['Name the harm','Offer repair','Make an excuse'],'Just Listen':['Listen without fixing','Ask what is needed','Give advice immediately']};
function startGrowingDialogue(force=null){const gt=DATA.growingTogether;let fi=force?gt.features.indexOf(force):rand(gt.features.length);if(fi<0)fi=0;const title=gt.features[fi],text=`${pick(gt.leads)}\n\n${pick(gt.scenarios[fi])}\n\n${pick(gt.endings)}`;const choices=featureResponses[title]||['Listen and connect','Make a practical plan','Dismiss the concern'];showDialogue({type:'GROWING TOGETHER',title,text,choices,onChoice:i=>{const pos=i<2;state.narrative.security=clamp(state.narrative.security+(pos?2:-2));state.narrative.resilience=clamp(state.narrative.resilience+(i===1?2:0));state.narrative.openness=clamp(state.narrative.openness+(i===0?3:i===2?-3:1));applyChange(pos?{bond:2,trust:2}:{bond:-3,trust:-2});addMemory(`${title}: ${choices[i]}.`);dialogueReply(pos?'I feel heard. I will remember how we handled this.':'I am not sure I feel understood yet.');}});}
function maybeDailyEvent(){const d=new Date(),key=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;if(state._eventDay===key)return;state._eventDay=key;if(Math.random()<.38){const e=pick(DATA.lifeEvents.filter(e=>eventAgeValid(e)));state.pendingEvent=e;}}
function eventAgeValid(e){const id=e.id;if(state.pet.stage==='baby')return id<=32;if(state.pet.stage==='child')return id<=80||id<17;if(state.pet.stage==='teen')return id<17||(id>=49&&id<=96);if(state.pet.stage==='adult')return id<17||id>=65;return id<17||id>=81;}
function openPendingEvent(){const e=state.pendingEvent;if(!e)return toast('No event waiting.');showDialogue({type:'LIFE EVENT',title:e.title,text:e.prompt,choices:e.choices,onChoice:i=>{applyChange(i===0?{bond:1,kindness:2}:{trust:1,responsibility:2});addMemory(`${e.title}: chose ${e.choices[i]}.`);state.pendingEvent=null;dialogueReply('That choice will affect what happens next.');}});}
function openNarrative(){menu('Growing Together',[{icon:'💬',label:'Parent check-in',desc:'Age-appropriate conversation',action:startParentDialogue},{icon:'📚',label:'Story and values',desc:'8,100 prompt combinations',action:()=>startGrowingDialogue()},{icon:'❗',label:'Life event',desc:state.pendingEvent?state.pendingEvent.title:'No event waiting',action:openPendingEvent},{icon:'📔',label:'Memories',desc:`${state.narrative.memories.length} saved`,action:openMemories},{icon:'🎁',label:'Keepsakes',desc:`${state.narrative.keepsakes.length} items`,action:openMemories},{icon:'📊',label:'Parent reflection',desc:'Relationship patterns',action:openReflection}], 'RELATIONSHIP');}
function openMemories(){showModal('Memories',state.narrative.memories.length?`<div class="log">${state.narrative.memories.map(m=>`<div>${new Date(m.at).toLocaleDateString()} · ${m.text}</div>`).join('')}</div>`:'<div class="empty">No memories yet.</div>','JOURNAL');}
function openReflection(){const n=state.narrative;showModal('Parent Reflection',`<div class="cards">${[['Security',n.security],['Openness',n.openness],['Confidence',n.confidence],['Empathy',n.empathy],['Honesty',n.honesty],['Responsibility',n.responsibility]].map(([a,b])=>`<div class="stat-card"><small>${a}</small><br><b>${Math.round(b)}</b></div>`).join('')}</div><div class="panel"><p>${n.openness>60?`${state.pet.name} usually feels safe bringing concerns to you.`:`${state.pet.name} may need more calm listening before opening up.`}</p></div>`,'BOND');}

function openGarden(){const html=state.garden.plots.map((p,i)=>`<div class="panel"><div class="row"><b>Plot ${i+1}</b><span>${p?p.species:'Empty'}</span></div>${p?`<small>Growth ${Math.round(p.growth)}% · Water ${Math.round(p.water)} · Health ${Math.round(p.health)}</small>`:'<small>Plant a crop here.</small>'}<div class="game-buttons"><button data-plot="${i}" data-act="plant">Plant</button><button data-plot="${i}" data-act="water">Water</button><button data-plot="${i}" data-act="harvest">Harvest</button></div></div>`).join('');showModal('Garden',html,'BOTANY');$$('[data-plot]').forEach(b=>b.onclick=()=>gardenAction(b.dataset.act,+b.dataset.plot));}
function gardenAction(act,index=0){const plots=state.garden.plots;let p=plots[index];if(act==='plant'){if(p)return toast('Plot is occupied.');if(state.inventory.seeds<=0)return toast('Buy seeds first.');state.inventory.seeds--;plots[index]={species:pick(DATA.crops),growth:0,water:80,health:100};}else if(!p)return toast('That plot is empty.');else if(act==='water')p.water=100;else if(act==='tend')p.health=clamp(p.health+25);else if(act==='harvest'){if(p.growth<90)return toast('Not ready yet.');state.inventory.materials+=2;state.pet.coins+=15;state.collections.plants.push(p.species);plots[index]=null;unlockAchievement('First Harvest');}queueSave();openGarden();}
function openAquarium(){const fish=state.aquarium.fish;showModal('Aquarium',`<div class="panel"><div class="row"><b>Water</b><span>Clean ${Math.round(state.aquarium.clean)} · Quality ${Math.round(state.aquarium.quality)}</span></div></div>${fish.length?fish.map((f,i)=>`<div class="panel"><div class="row"><b>${f.name}</b><span>${f.species}</span></div><small>Hunger ${Math.round(f.hunger)} · Mood ${Math.round(f.mood)}</small></div>`).join(''):'<div class="empty">No fish yet.</div>'}<div class="game-buttons"><button id="aqFeed">Feed</button><button id="aqClean">Clean</button><button id="aqAdopt">Adopt</button></div>`,'AQUARIUM');$('#aqFeed').onclick=()=>aquariumAction('feed');$('#aqClean').onclick=()=>aquariumAction('clean');$('#aqAdopt').onclick=()=>aquariumAction('adopt');}
function aquariumAction(act){if(act==='adopt'){if(state.aquarium.fish.length>=6)return toast('Tank is full.');if(state.pet.coins<25)return toast('Need 25 coins.');state.pet.coins-=25;const sp=pick(DATA.fish);state.aquarium.fish.push({species:sp,name:sp.split(' ')[0],hunger:80,mood:80});state.collections.fish.push(sp);}else if(act==='feed'){for(const f of state.aquarium.fish)f.hunger=clamp(f.hunger+35);}else{state.aquarium.clean=100;state.aquarium.quality=100;}queueSave();openAquarium();}
function openDecor(){menu('Room Themes',['Cozy Cottage','Modern Apartment','Space Station','Forest Cabin','Aquarium Room','Music Studio','Royal Room','Haunted Room'].map((r,i)=>({icon:['🏡','🏢','🚀','🌲','🐟','🎹','👑','👻'][i],label:r,desc:state.inventory.rooms.includes(r)?'Owned':'Unlock 50 coins',action:()=>{if(!state.inventory.rooms.includes(r)){if(state.pet.coins<50)return toast('Need 50 coins.');state.pet.coins-=50;state.inventory.rooms.push(r);}state.roomTheme=r;queueSave();closeModal();toast(`${r} selected.`);}})),'DECOR');}
function openShop(){menu('Market',[{icon:'🍙',label:'Food pack',desc:'3 meals · 18 coins',action:()=>buy('food',3,18)},{icon:'🍰',label:'Snack pack',desc:'3 snacks · 15 coins',action:()=>buy('snacks',3,15)},{icon:'🌱',label:'Seeds',desc:'3 seeds · 20 coins',action:()=>buy('seeds',3,20)},{icon:'💊',label:'Medicine',desc:'1 dose · 25 coins',action:()=>buy('medicine',1,25)},{icon:'🎩',label:'Fancy hat',desc:'New hat · 40 coins',action:()=>buyHat()}],'MARKET');}
function shopCategory(){openShop();}function buy(k,n,c){if(state.pet.coins<c)return toast('Not enough coins.');state.pet.coins-=c;state.inventory[k]+=n;queueSave();toast('Purchased.');}
function buyHat(){if(state.pet.coins<40)return toast('Not enough coins.');state.pet.coins-=40;state.inventory.hats.push(`Hat ${state.inventory.hats.length+1}`);queueSave();toast('New fancy hat!');}
function cityReward(type){if(type==='kind'){applyChange({kindness:3,bond:1});state.pet.coins+=8;}else{applyChange({fitness:2,fun:6});state.inventory.materials++;}toast('Activity complete.');}
function openNeighbors(){menu('Neighbors',DATA.neighbors.map(n=>{const r=state.relationships[n];return{icon:r.met?'😊':'❔',label:n,desc:`Bond ${r.bond}`,action:()=>{r.met=true;r.bond=clamp(r.bond+5);applyChange({fun:5});toast(`Visited ${n}.`);queueSave();openNeighbors();}}}),'RELATIONSHIPS');}
function neighborAction(){const n=pick(DATA.neighbors);const r=state.relationships[n];if(state.pet.coins<5)return toast('Need a small gift.');state.pet.coins-=5;r.met=true;r.bond=clamp(r.bond+10);toast(`${n} loved the gift.`);queueSave();}
function openFamily(){const p=state.pet;const bonded=Object.entries(state.relationships).filter(([,r])=>r.bond>=60);let items=[{icon:'💗',label:p.spouse?`Spouse: ${p.spouse.name}`:'Choose partner',desc:p.stage==='adult'||p.stage==='elder'?'Adult family life':'Unlocks as adult',action:()=>choosePartner(bonded)},{icon:'👶',label:`Children: ${p.children.length}`,desc:'Generations and inheritance',action:addChild},{icon:'🐾',label:p.companion||'Adopt companion',desc:'Bonded helper pet',action:adoptCompanion},{icon:'🌳',label:`Generation ${p.generation}`,desc:'Family legacy',action:openCollections}];menu('Family',items,'FAMILY');}
function choosePartner(bonded){if(!['adult','elder'].includes(state.pet.stage))return toast('Marriage unlocks as an adult.');if(!bonded.length)return toast('Build a neighbor bond to 60 first.');menu('Choose Partner',bonded.map(([n,r])=>({icon:'💗',label:n,desc:`Bond ${r.bond}`,action:()=>{state.pet.spouse={name:n,species:rand(50),bond:r.bond};addMemory(`Married ${n}.`);queueSave();closeModal();toast(`${n} moved in.`);}})),'PARTNER');}
function addChild(){if(!state.pet.spouse)return toast('Choose a partner first.');if(state.pet.children.length>=3)return toast('Family is full.');state.pet.children.push({name:`Child ${state.pet.children.length+1}`,species:(state.pet.species+state.pet.spouse.species+rand(10))%50,bond:50});addMemory('A new child joined the family.');queueSave();openFamily();}
function adoptCompanion(){if(state.pet.companion)return toast('You already have a companion.');if(state.pet.coins<40)return toast('Need 40 coins.');state.pet.coins-=40;state.pet.companion=pick(DATA.companions);addMemory(`Adopted ${state.pet.companion}.`);queueSave();openFamily();}

function openCareer(){if(!['adult','elder'].includes(state.pet.stage))return toast('Careers unlock in adulthood.');menu('Choose Career',DATA.careers.map((c,i)=>({icon:['🍳','🎵','🔬','🌿','🩺','📚','🎨','🚀','🛍','🏅'][i],label:c,desc:state.pet.career===c?'Current career':'Work weekdays 9–5',action:()=>{state.pet.career=c;addMemory(`Started a career as a ${c}.`);queueSave();closeModal();toast(`${c} career selected.`);}})),'CAREER');}
function openStatus(){const p=state.pet,s=scheduleFor(p.stage),d=new Date(),h=d.getHours()+d.getMinutes()/60,dayStart=s.wake,dayEnd=s.bed,percent=((h-dayStart+24)%24)/((dayEnd-dayStart+24)%24)*100;showModal('Status',`<div class="cards">${[['Coins',Math.floor(p.coins)],['Age',`${(p.ageMinutes/1440).toFixed(1)}d`],['Generation',p.generation],['Care misses',p.careMisses],['School XP',Math.floor(p.schoolXP)],['Career XP',Math.floor(p.careerXP)]].map(([a,b])=>`<div class="stat-card"><small>${a}</small><br><b>${b}</b></div>`).join('')}</div><div class="panel"><h3>Today</h3><div class="timeline"><i style="left:${clamp(percent)}%"></i><span style="left:5%">Wake</span><span style="left:50%">Day</span><span style="left:95%">Bed</span></div><p style="margin-top:2.4rem">${fmtDay(d)} ${fmtTime(d)} · ${currentActivity()}</p></div><div class="panel"><h3>Personality</h3><p>${p.emotion} · Intelligence ${Math.round(p.intelligence)} · Kindness ${Math.round(p.kindness)} · Fitness ${Math.round(p.fitness)} · Discipline ${Math.round(p.discipline)}</p></div>`,'STATUS');}
function openCollections(){showModal('Collections',`<div class="cards">${[['Species',new Set(state.collections.species).size+'/50'],['Fish',new Set(state.collections.fish).size+'/12'],['Plants',new Set(state.collections.plants).size+'/12'],['Achievements',state.collections.achievements.length],['Museum',state.collections.museum.length],['Keepsakes',state.narrative.keepsakes.length]].map(([a,b])=>`<div class="stat-card"><small>${a}</small><br><b>${b}</b></div>`).join('')}</div><div class="panel"><h3>Achievements</h3>${state.collections.achievements.length?state.collections.achievements.map(a=>`<div>🏆 ${a}</div>`).join(''):'<p>No achievements yet.</p>'}</div>`,'MUSEUM');}
function unlockAchievement(a){if(!state.collections.achievements.includes(a)){state.collections.achievements.push(a);toast(`Achievement: ${a}`);}}
function openGoals(){ensureGoals();showModal('Goals',`<div class="panel"><h3>Daily</h3>${state.goals.daily.map(g=>`<div>☐ ${g}</div>`).join('')}</div><div class="panel"><h3>Weekly</h3>${state.goals.weekly.map(g=>`<div>☐ ${g}</div>`).join('')}</div>`,'GOALS');}
function ensureGoals(){const key=new Date().toDateString();if(state.goals.lastDay!==key){state.goals.lastDay=key;state.goals.daily=['Share a meal','Play one game','Check a plant'];if(!state.goals.weekly.length)state.goals.weekly=['Make a new memory','Harvest a crop','Visit a neighbor'];}}
function checkGoals(){ensureGoals();}

async function loadTracks(){tracks=await idbAll('tracks');tracks.sort((a,b)=>a.artist.localeCompare(b.artist)||a.title.localeCompare(b.title));}
function parseTrack(file){const raw=file.name.replace(/\.mp3$/i,'');let artist='Unknown Artist',title=raw;if(raw.includes('_'))[artist,title]=[raw.slice(0,raw.indexOf('_')),raw.slice(raw.indexOf('_')+1).replaceAll('_',' ')];else if(file.webkitRelativePath){const parts=file.webkitRelativePath.split('/');if(parts.length>1)artist=parts.at(-2);}return{artist:artist.trim(),title:title.trim(),filename:file.name,blob:file,addedAt:now()};}
async function importMusic(files){let count=0;for(const f of files){if(!/\.mp3$/i.test(f.name)&&f.type!=='audio/mpeg')continue;await idbPut('tracks',parseTrack(f));count++;}await loadTracks();toast(`Imported ${count} songs.`);openMusic();}
function openMusic(){const playing=currentTrackIndex>=0?tracks[currentTrackIndex]:null;showModal('Music Disc',`${playing?`<div class="panel music-player"><div class="disc ${audio.paused?'paused':''}"></div><div><b>${playing.title}</b><small>${playing.artist}</small><div class="player-controls"><button id="mpPrev">◀</button><button id="mpToggle">${audio.paused?'▶':'Ⅱ'}</button><button id="mpNext">▶</button><button id="mpFav">${state.music.favorites.includes(playing.id)?'★':'☆'}</button></div></div></div>`:''}<div class="menu-grid"><button class="menu-item" id="allSongs"><span class="glyph">🎵</span><span><strong>All Songs</strong><small>${tracks.length} imported</small></span></button><button class="menu-item" id="artists"><span class="glyph">🎤</span><span><strong>Artists</strong><small>Browse folders</small></span></button><button class="menu-item" id="favorites"><span class="glyph">★</span><span><strong>Favorites</strong><small>${state.music.favorites.length} songs</small></span></button><button class="menu-item" id="recent"><span class="glyph">🕘</span><span><strong>Recent</strong><small>${state.music.recent.length} songs</small></span></button><button class="menu-item" id="addFiles"><span class="glyph">＋</span><span><strong>Add MP3 files</strong><small>Store on this phone</small></span></button><button class="menu-item" id="addFolder"><span class="glyph">📁</span><span><strong>Add music folder</strong><small>Artist folders supported</small></span></button></div><div class="panel"><label>Volume <input id="musicVolume" type="range" min="0" max="1" step="0.01" value="${state.music.volume}"></label></div>`,'MUSIC');$('#allSongs').onclick=()=>showTrackList(tracks,'All Songs');$('#artists').onclick=openArtists;$('#favorites').onclick=()=>showTrackList(tracks.filter(t=>state.music.favorites.includes(t.id)),'Favorites');$('#recent').onclick=()=>showTrackList(state.music.recent.map(id=>tracks.find(t=>t.id===id)).filter(Boolean),'Recent');$('#addFiles').onclick=()=>$('#musicFiles').click();$('#addFolder').onclick=()=>$('#musicFolder').click();$('#musicVolume').oninput=e=>{state.music.volume=+e.target.value;audio.volume=state.music.volume;queueSave();};if(playing){$('#mpPrev').onclick=previousTrack;$('#mpToggle').onclick=toggleAudio;$('#mpNext').onclick=nextTrack;$('#mpFav').onclick=toggleFavorite;}}
function showTrackList(list,title){showModal(title,list.length?list.map(t=>`<div class="track-row"><button class="trackPlay" data-id="${t.id}" style="text-align:left"><b>${t.title}</b><small>${t.artist}</small></button><button class="trackFav" data-id="${t.id}">${state.music.favorites.includes(t.id)?'★':'☆'}</button></div>`).join(''):'<div class="empty">No songs here. Import MP3 files first.</div>','MUSIC');$$('.trackPlay').forEach(b=>b.onclick=()=>playTrackById(+b.dataset.id));$$('.trackFav').forEach(b=>b.onclick=()=>{toggleFavorite(+b.dataset.id);showTrackList(list,title);});}
function openArtists(){const artists=[...new Set(tracks.map(t=>t.artist))];menu('Artists',artists.map(a=>({icon:'🎤',label:a,desc:`${tracks.filter(t=>t.artist===a).length} songs`,action:()=>showTrackList(tracks.filter(t=>t.artist===a),a)})),'MUSIC');}
async function playTrackById(id){const i=tracks.findIndex(t=>t.id===id);if(i<0)return;currentTrackIndex=i;const t=tracks[i];if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(t.blob);audio.src=objectUrl;audio.volume=state.music.volume;await audio.play();state.music.recent=[id,...state.music.recent.filter(x=>x!==id)].slice(0,20);queueSave();setMediaSession(t);closeModal();render();}
function setMediaSession(t){if('mediaSession'in navigator&&'MediaMetadata'in window){navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:'Pico Tamachibi Music Disc',artwork:[{src:'icons/icon-512.png',sizes:'512x512',type:'image/png'}]});navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',previousTrack);navigator.mediaSession.setActionHandler('nexttrack',nextTrack);}}
function toggleAudio(){audio.paused?audio.play():audio.pause();openMusic();}function previousTrack(){if(!tracks.length)return;playTrackById(tracks[(currentTrackIndex-1+tracks.length)%tracks.length].id);}function nextTrack(){if(!tracks.length)return;playTrackById(tracks[(currentTrackIndex+1)%tracks.length].id);}function toggleFavorite(id=tracks[currentTrackIndex]?.id){if(!id)return;const f=state.music.favorites;state.music.favorites=f.includes(id)?f.filter(x=>x!==id):[...f,id];queueSave();toast(state.music.favorites.includes(id)?'Added to favorites.':'Removed from favorites.');}
audio.onended=nextTrack;audio.onplay=render;audio.onpause=render;

function openSettings(){showModal('Settings',`<div class="stack"><label class="panel toggle"><input id="notifyToggle" type="checkbox" ${state.settings.notifications?'checked':''}> Care notifications</label><label class="panel">Difficulty<select id="difficulty" style="width:100%;margin-top:.4rem"><option>relaxed</option><option>normal</option><option>challenge</option><option>sandbox</option></select></label><button id="exportBtn">Export save</button><button id="importBtn">Import save</button><button id="renameBtn">Rename Tamagotchi</button><button id="newGenBtn">Begin next generation</button><button id="resetBtn" class="danger">Full reset</button></div>`,'SETTINGS');$('#difficulty').value=state.settings.difficulty;$('#difficulty').onchange=e=>{state.settings.difficulty=e.target.value;queueSave();};$('#notifyToggle').onchange=async e=>{if(e.target.checked)await enableNotifications();else{state.settings.notifications=false;queueSave();}};$('#exportBtn').onclick=exportSave;$('#importBtn').onclick=()=>$('#importSave').click();$('#renameBtn').onclick=renamePet;$('#newGenBtn').onclick=nextGeneration;$('#resetBtn').onclick=resetGame;}
function renamePet(){const name=prompt('New name',state.pet.name);if(name){state.pet.name=name.slice(0,18);queueSave();render();}}
function nextGeneration(){if(!confirm('Start a new generation? Long-term collections and legacy stay.'))return;const old=state.pet;state.narrative.keepsakes.push(`${old.name}'s legacy`);state.pet={...newState().pet,name:old.children[0]?.name||'Mochi',species:old.children[0]?.species??rand(50),generation:old.generation+1,bornAt:now()};addMemory(`Generation ${state.pet.generation} began.`);queueSave();closeModal();render();}
async function resetGame(){if(!confirm('Erase the complete save?'))return;state=newState();await saveState();closeModal();render();}
function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tamachibi-save-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
async function importSaveFile(file){try{const data=JSON.parse(await file.text());if(!data.pet||!data.version)throw new Error('Invalid save');state=data;normalizeState();await saveState();toast('Save imported.');closeModal();render();}catch(e){toast('Could not import save.');}}
function openMore(){menu('More',[{icon:'📊',label:'Status',desc:'Needs, schedule, personality',action:openStatus},{icon:'🎯',label:'Goals',desc:'Daily and weekly goals',action:openGoals},{icon:'🏛',label:'Collections',desc:'Species, fish, plants, trophies',action:openCollections},{icon:'👪',label:'Family',desc:'Partner, children, generations',action:openFamily},{icon:'📔',label:'Growing Together',desc:'Stories, memories, reflection',action:openNarrative},{icon:'⚙',label:'Settings',desc:'Notifications, backup, reset',action:openSettings}], 'MORE');}
function openWorld(){menu('World',[{icon:'🏡',label:'Home rooms',desc:'Kitchen, garden, aquarium, family',action:()=>{view='home';closeModal();render();}},{icon:'🏙',label:'City',desc:'Market, neighbors, clinic, museum',action:()=>{view='city';closeModal();render();}},{icon:'🐾',label:'Tamagotchi',desc:'Return to your pet',action:()=>{view='tama';closeModal();render();}},{icon:'🌿',label:'Garden',desc:'Crops and harvest',action:openGarden},{icon:'🐟',label:'Aquarium',desc:'Fish and tank care',action:openAquarium},{icon:'👪',label:'Family',desc:'Relationships and legacy',action:openFamily}], 'WORLD');}

async function enableNotifications(){if(!('Notification'in window))return toast('Notifications are not supported here.');const perm=await Notification.requestPermission();if(perm!=='granted')return toast('Notification permission was not granted.');state.settings.notifications=true;queueSave();const reg=await navigator.serviceWorker?.ready;await reg?.showNotification('Pico Tamachibi',{body:`${state.pet.name} can now send care alerts.`,icon:'icons/icon-192.png',tag:'tamachibi-test'});try{if(reg?.periodicSync)await reg.periodicSync.register('tamachibi-care',{minInterval:15*60*1000});}catch(e){}toast('Notifications enabled.');}
function urgentMessage(){const p=state.pet,act=currentActivity();if(act!=='home')return null;if(p.sick||p.needs.health<20)return`${p.name} needs medical care.`;if(p.poop>=2||p.needs.clean<15)return`${p.name} needs cleaning.`;if(p.needs.food<15)return`${p.name} is very hungry.`;if(p.needs.energy<15)return`${p.name} is exhausted.`;if(p.needs.fun<15)return`${p.name} feels lonely.`;if(state.garden.plots.some(x=>x&&x.water<10))return'The garden needs water.';if(state.aquarium.fish.length&&state.aquarium.clean<20)return'The aquarium needs cleaning.';return null;}
async function checkCareNotification(){if(!state.settings.notifications||Notification.permission!=='granted')return;const msg=urgentMessage();if(!msg||now()-state.notifications.lastShown<45*60*1000)return;state.notifications.lastShown=now();state.notifications.log.unshift({msg,at:now()});const reg=await navigator.serviceWorker.ready;reg.showNotification('Pico Tamachibi needs you',{body:msg,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:'tamachibi-care',renotify:true,data:{url:'./?open=care'}});queueSave();}

function handlePanel(panel){({care:()=>menu('Care',[{icon:'🍙',label:'Meal',desc:`${state.inventory.food} available`,action:()=>feed(false)},{icon:'🍰',label:'Snack',desc:`${state.inventory.snacks} available`,action:()=>feed(true)},{icon:'🧼',label:'Clean',desc:`Poop ${state.pet.poop}`,action:cleanPet},{icon:'💊',label:'Medicine',desc:state.pet.sick?'Sick now':'Healthy',action:healPet},{icon:'😴',label:'Sleep schedule',desc:`Bed ${formatHour(scheduleFor(state.pet.stage).bed)}`,action:openBedtime},{icon:'📊',label:'Needs',desc:'Full status',action:openStatus}],'CARE'),play:openPlay,talk:openNarrative,world:openWorld,music:openMusic,more:openMore})[panel]?.();}

function bindUI(){$$('.view-switch button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();queueSave();});$('#prevScene').onclick=()=>{if(view==='home')roomIndex=(roomIndex-1+DATA.rooms.length)%DATA.rooms.length;else if(view==='city')cityIndex=(cityIndex-1+DATA.city.length)%DATA.city.length;render();queueSave();};$('#nextScene').onclick=()=>{if(view==='home')roomIndex=(roomIndex+1)%DATA.rooms.length;else if(view==='city')cityIndex=(cityIndex+1)%DATA.city.length;render();queueSave();};$$('.bottom-nav button').forEach(b=>b.onclick=()=>handlePanel(b.dataset.panel));$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};$('#musicFiles').onchange=e=>importMusic(e.target.files);$('#musicFolder').onchange=e=>importMusic(e.target.files);$('#importSave').onchange=e=>e.target.files[0]&&importSaveFile(e.target.files[0]);$('#notifyBtn').onclick=enableNotifications;$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden');}else toast('Use your browser menu and choose Install app.');};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden');});window.addEventListener('pagehide',saveState);document.addEventListener('visibilitychange',async()=>{if(document.hidden)await saveState();else{const elapsed=Math.floor((now()-state.savedAt)/60000);if(elapsed>0)advanceMinutes(elapsed,true);render();}});}

async function registerSW(){if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js');navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='OPEN_PANEL')handlePanel(e.data.panel);});return reg;}}
async function init(){db=await openDB();await loadState();applyOffline();await loadTracks();bindUI();await registerSW();try{await navigator.storage?.persist?.();}catch(e){}ensureGoals();render();setInterval(tick,1000);setInterval(checkCareNotification,120000);const q=new URLSearchParams(location.search).get('open');if(q)setTimeout(()=>handlePanel(q),500);if(state.summary.length)setTimeout(()=>toast(state.summary[0]),700);}
init().catch(e=>{console.error(e);document.body.innerHTML=`<main style="padding:2rem;color:white"><h1>Could not start Pico Tamachibi</h1><pre>${e.stack||e}</pre></main>`;});
