import {DATA} from './data.js';
import {openDB,idbGet,idbPut,idbDelete,idbAll,idbClear} from './db.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(n,a=0,b=10)=>Math.max(a,Math.min(b,n));
const rand=n=>Math.floor(Math.random()*n), pick=a=>a[rand(a.length)], now=()=>Date.now();
const TICK_MS=300000, TICKS_PER_DAY=288;
const STAGES=['egg','baby','child','teen','adult','elder'];
const STAGE_AT={egg:0,baby:1,child:288,teen:864,adult:1728,elder:5760};
const ACTIVITY_LABEL={home:'HOME',school:'AT SCHOOL',work:'AT WORK',sleep:'SLEEPING',sitter:'WITH SITTER'};

let state=null, ui={screen:'scene',world:0,menuIndex:0,roomIndex:0,cityIndex:0,eggIndex:0,eggChoices:[],frame:0};
let saveTimer=null, holdTimer=null, holdTriggered=false, deferredInstall=null;
let currentTrack=-1, tracks=[], objectURL=null, game=null, audioCtx=null;
const main=$('#mainCanvas'), mctx=main.getContext('2d'), status=$('#statusCanvas'), sctx=status.getContext('2d');
const dialogueCanvas=$('#dialogueCanvas'), dctx=dialogueCanvas.getContext('2d'), audio=$('#audio');
for(const c of [mctx,sctx,dctx]) c.imageSmoothingEnabled=false;

function emptyPlot(){return null;}
function baseState(){const t=now();return{
 version:2,createdAt:t,savedAt:t,lastTickAt:t,remainderMs:0,profile:'main',
 settings:{sound:true,notifications:false,reducedMotion:false,difficulty:'normal',careAlerts:true,autoSave:true},
 pet:{name:'Tama',stage:'egg',eggType:0,species:0,birthCode:0,ageTicks:0,generation:1,temperament:rand(8),personality:rand(8),
  stats:{health:8,full:7,energy:7,happy:7,clean:8,discipline:5},skills:{smart:0,style:0,kind:0,fit:0},
  ownerBond:25,ownerTrust:25,poop:0,sick:false,condition:0,dead:false,sleeping:false,careMistakes:0,stageCareMistakes:0,
  foodZeroTicks:0,cleanZeroTicks:0,happyZeroTicks:0,sickTicks:0,criticalTicks:0,weight:5,coins:10,
  career:null,careerXP:0,jobRank:0,schoolXP:0,spouse:null,children:[],companion:null,outfit:0,roomStyle:0,
  favoriteFood:0,favoriteGame:0,album:[],lastConversationAt:0,lastEventDay:-1,sitterUntil:0},
 inventory:{meals:6,snacks:4,medicine:2,berries:2,herbs:2,veg:2,spice:1,seeds:6,materials:0,hats:[0],rooms:[0],toys:[]},
 garden:{plots:Array.from({length:4},emptyPlot),indoor:Array.from({length:4},emptyPlot),harvests:0},
 aquarium:{clean:90,quality:90,fish:[]},
 city:{relationships:Object.fromEntries(DATA.neighbors.map(n=>[n,{met:false,bond:0,quest:0}])),projects:{school:0,park:0,clinic:0,market:0,museum:0,spaceport:0},reputation:{helpful:0,playful:0,reliable:0,famous:0,adventurous:0}},
 paradise:{level:0,research:0,biofuel:0,missions:Array(DATA.paradiseMissions.length).fill(false),fields:['Land'],currentField:'Land',toys:[],travel:[],codes:[],lastEggHuntDay:-1,emergencies:0},
 narrative:{openness:50,confidence:45,empathy:45,honesty:50,resilience:45,responsibility:40,independence:30,security:50,
  promises:[],keepsakes:[],traditions:[],memories:[],history:[],activeArc:null,parentStyle:{comfort:0,listen:0,coach:0,boundary:0,encourage:0,independence:0,dismiss:0,mischief:0}},
 collections:{species:[],fish:[],plants:[],achievements:[],museum:[],titles:[],scrapbook:[]},
 gameCounts:Object.fromEntries([...DATA.arcadeGames,...Object.values(DATA.lifeStageGames).flat()].map(n=>[n,0])),
 music:{favorites:[],recent:[],volume:.65,shuffle:false},notifications:{lastShown:0,log:[]},summary:[]
};}

function normalize(){const n=baseState();for(const k of Object.keys(n)) if(state[k]===undefined) state[k]=structuredClone(n[k]);state.pet.stats={...n.pet.stats,...state.pet.stats};state.pet.skills={...n.pet.skills,...state.pet.skills};state.settings={...n.settings,...state.settings};state.music={...n.music,...state.music};state.narrative={...n.narrative,...state.narrative};}
function makeEggChoices(){const used=new Set(),out=[];while(out.length<4){const n=rand(50);if(!used.has(n)){used.add(n);out.push(n)}}return out;}
function stageForTicks(t){if(t<1)return'egg';if(t<288)return'baby';if(t<864)return'child';if(t<1728)return'teen';if(t<5760)return'adult';return'elder';}
function schedule(stage){return{egg:{bed:24,wake:0},baby:{bed:19,wake:7},child:{bed:20,wake:7,school:[8,15]},teen:{bed:22,wake:7,school:[8,15]},adult:{bed:23,wake:6,work:[9,17]},elder:{bed:21,wake:6}}[stage]||{bed:20,wake:7};}
function currentActivity(date=new Date()){const p=state.pet;if(p.stage==='egg')return'home';if(p.sitterUntil>now())return'sitter';const s=schedule(p.stage),h=date.getHours()+date.getMinutes()/60,weekend=[0,6].includes(date.getDay());const asleep=s.bed>s.wake?(h>=s.bed||h<s.wake):(h>=s.bed&&h<s.wake);if(asleep)return'sleep';if(!weekend&&s.school&&h>=s.school[0]&&h<s.school[1])return'school';if(!weekend&&s.work&&p.career&&h>=s.work[0]&&h<s.work[1])return'work';return'home';}
function difficulty(){return{relaxed:.65,normal:1,challenge:1.35,sandbox:.25}[state.settings.difficulty]||1;}
function addMemory(text){state.narrative.memories.unshift({text,at:now()});state.narrative.memories=state.narrative.memories.slice(0,120);state.collections.scrapbook.unshift({text,at:now()});state.collections.scrapbook=state.collections.scrapbook.slice(0,120);}
function addStat(key,n){state.pet.stats[key]=clamp(state.pet.stats[key]+n);}
function addSkill(key,n){state.pet.skills[key]=clamp(state.pet.skills[key]+n,0,99);}
function changeBond(n){state.pet.ownerBond=clamp(state.pet.ownerBond+n,0,100);}
function changeTrust(n){state.pet.ownerTrust=clamp(state.pet.ownerTrust+n,0,100);}
function markAchievement(name){if(!state.collections.achievements.includes(name)){state.collections.achievements.push(name);toast(`Achievement: ${name}`)}}

async function load(){state=await idbGet('kv','state');if(!state){state=baseState();ui.eggChoices=makeEggChoices();ui.screen='eggSelect';}else{normalize();ui.world=state.ui?.world||0;ui.roomIndex=state.ui?.roomIndex||0;ui.cityIndex=state.ui?.cityIndex||0;ui.screen=state.pet.dead?'scene':'scene';}}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,250);}
async function save(){if(!state)return;state.savedAt=now();state.ui={world:ui.world,roomIndex:ui.roomIndex,cityIndex:ui.cityIndex};await idbPut('kv',structuredClone(state),'state');}

function applyOffline(){const elapsed=now()-(state.savedAt||now());if(elapsed<=0)return;const total=elapsed+(state.remainderMs||0),ticks=Math.floor(total/TICK_MS);state.remainderMs=total%TICK_MS;if(ticks>0){advanceTicks(Math.min(ticks,8640),true);state.summary.unshift(`While you were away for ${prettyTicks(ticks)}, ${state.pet.name} followed the real-day schedule.`);state.summary=state.summary.slice(0,10);}state.lastTickAt=now();}
function prettyTicks(t){const min=t*5;if(min<60)return`${min} min`;const h=Math.floor(min/60);if(h<24)return`${h}h ${min%60}m`;return`${Math.floor(h/24)}d ${h%24}h`;}
function updateStage(){const p=state.pet,old=p.stage,next=stageForTicks(p.ageTicks);if(old===next)return;p.stage=next;p.stageCareMistakes=0;if(next==='baby'){addMemory(`${p.name} hatched.`);toast('The egg hatched!');p.stats={health:8,full:7,energy:7,happy:7,clean:8,discipline:5};}
 else{addMemory(`${p.name} evolved to ${next}.`);toast(`${p.name} became a ${next}!`);if(next==='adult'&&!state.collections.species.includes(p.species))state.collections.species.push(p.species);}checkParadiseMissions();}
function careMistake(flag){if(!flag)return;state.pet.careMistakes++;state.pet.stageCareMistakes++;state.pet.ownerTrust=clamp(state.pet.ownerTrust-1,0,100);}
function advanceOneTick(date){const p=state.pet;if(p.dead)return;p.ageTicks++;updateStage();if(p.stage==='egg')return;const act=currentActivity(date),rate=difficulty();p.sleeping=act==='sleep';
 if(act==='sleep'){if(p.ageTicks%72===0)addStat('full',-1);if(p.ageTicks%12===0)addStat('energy',1);if(p.ageTicks%24===0&&p.condition>0)p.condition--;}
 else if(act==='school'||act==='work'||act==='sitter'){if(act==='school'){p.schoolXP+=1/12;if(p.ageTicks%12===0)addSkill('smart',1);}if(act==='work'){p.careerXP+=1/12;if(p.ageTicks%12===0)p.coins+=1;}if(p.ageTicks%18===0)addStat('energy',-1);if(new Date(date).getHours()===12&&new Date(date).getMinutes()<5)addStat('full',1);}
 else{if(p.ageTicks%Math.max(1,Math.round(12/rate))===0)addStat('full',-1);if(p.ageTicks%Math.max(1,Math.round(18/rate))===0)addStat('energy',-1);if(p.ageTicks%Math.max(1,Math.round(24/rate))===0)addStat('happy',-1);const poopChance=p.stats.discipline>=7?180:p.stats.discipline<=3?72:120;if(p.stats.full>0&&rand(poopChance)===0)p.poop=Math.min(3,p.poop+1);}
 if(p.poop>0&&p.ageTicks%12===0)addStat('clean',-1);
 p.foodZeroTicks=p.stats.full===0?p.foodZeroTicks+1:0;p.cleanZeroTicks=p.stats.clean===0?p.cleanZeroTicks+1:0;p.happyZeroTicks=p.stats.happy===0?p.happyZeroTicks+1:0;p.sickTicks=(p.sick||p.condition)?p.sickTicks+1:0;
 if(p.foodZeroTicks===72)careMistake(true);if(p.cleanZeroTicks===96)careMistake(true);if(p.happyZeroTicks===288)careMistake(true);if(p.sickTicks===144)careMistake(true);
 const bad=(p.stats.clean<=2||p.stats.full===0||p.stats.energy<=1);if(bad&&p.ageTicks%18===0&&rand(18)===0){p.sick=true;p.condition=Math.max(p.condition,1);}
 if((p.foodZeroTicks>576||p.cleanZeroTicks>576||p.sickTicks>576)&&p.ageTicks%48===0)addStat('health',-1);if(p.sick&&p.ageTicks%96===0)addStat('health',-1);
 if(p.stats.health<=0){p.dead=true;addMemory(`${p.name}'s life ended.`);archivePet();}
 updateGardenTick();updateAquariumTick();updateParadiseTick();maybeLifeEvent();}
function advanceTicks(ticks,offline=false){let d=new Date(now()-ticks*TICK_MS);for(let i=0;i<ticks;i++){advanceOneTick(d);d=new Date(d.getTime()+TICK_MS);}if(offline)checkCareNotification();}
function updateGardenTick(){for(const plot of [...state.garden.plots,...state.garden.indoor])if(plot){if(plot.water>0){plot.growth=clamp(plot.growth+.18,0,100);plot.water=clamp(plot.water-.08,0,100);}else plot.health=clamp(plot.health-.08,0,100);}}
function updateAquariumTick(){if(!state.aquarium.fish.length)return;state.aquarium.clean=clamp(state.aquarium.clean-.03*state.aquarium.fish.length,0,100);state.aquarium.quality=clamp(state.aquarium.quality-.02*state.aquarium.fish.length,0,100);for(const f of state.aquarium.fish){f.hunger=clamp(f.hunger-.05,0,100);f.mood=clamp(f.mood+(state.aquarium.clean>50?.01:-.05),0,100);}}
function updateParadiseTick(){state.paradise.level=Math.min(10,Math.max(state.pet.stage==='child'?1:0,state.pet.stage==='teen'?2:0,state.pet.stage==='adult'?3:0,state.pet.generation>1?4:0,state.paradise.fields.length>=2?5:0));}
function tick(){const elapsed=now()-(state.lastTickAt||now())+(state.remainderMs||0),ticks=Math.floor(elapsed/TICK_MS);if(ticks>0){state.remainderMs=elapsed%TICK_MS;state.lastTickAt=now();advanceTicks(Math.min(ticks,288));queueSave();}ui.frame++;render();}

// ---------- 1-bit rendering ----------
function clear(c,w,h){c.fillStyle='#020303';c.fillRect(0,0,w,h);c.fillStyle='#f6f3df';c.strokeStyle='#f6f3df';c.lineWidth=1;}
function text(c,s,x,y,size=7,align='left'){c.font=`${size}px monospace`;c.textAlign=align;c.textBaseline='top';c.fillStyle='#f6f3df';c.fillText(String(s),x,y);c.textAlign='left';}
function line(c,x1,y1,x2,y2){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();}
function roundRect(c,x,y,w,h,r,fill=false){c.beginPath();c.roundRect(x,y,w,h,r);fill?c.fill():c.stroke();}
function drawEgg(c,x,y,type,selected=false){c.save();if(selected){c.fillStyle='#f6f3df';roundRect(c,x-4,y-4,28,31,5,true);c.fillStyle='#020303';c.strokeStyle='#020303';}else{c.fillStyle='#f6f3df';c.strokeStyle='#f6f3df';roundRect(c,x-4,y-4,28,31,5,false);}c.beginPath();c.arc(x+10,y+14,10,0,Math.PI*2);c.stroke();c.beginPath();c.arc(x+10,y+9,7,0,Math.PI*2);c.stroke();line(c,x+3,y+13,x+17,y+13);const p=type%10;if(p===0)line(c,x+5,y+17,x+15,y+17);else if(p===1){c.fillRect(x+6,y+10,1,1);c.fillRect(x+14,y+15,1,1);c.fillRect(x+9,y+20,1,1);}else if(p===2){c.beginPath();c.moveTo(x+10,y+8);c.lineTo(x+5,y+19);c.lineTo(x+15,y+19);c.closePath();c.stroke();}else if(p===3){line(c,x+4,y+16,x+7,y+13);line(c,x+7,y+13,x+10,y+16);line(c,x+10,y+16,x+13,y+13);line(c,x+13,y+13,x+16,y+16);}else if(p===4){c.beginPath();c.arc(x+10,y+15,3,0,Math.PI*2);c.stroke();}else if(p===5){line(c,x+5,y+11,x+15,y+11);line(c,x+5,y+19,x+15,y+19);}else if(p===6)c.strokeRect(x+7,y+12,7,7);else if(p===7){c.fillRect(x+7,y+13,1,1);c.fillRect(x+10,y+16,1,1);c.fillRect(x+13,y+13,1,1);}else if(p===8)roundRect(c,x+6,y+12,9,8,3,false);else{line(c,x+7,y+10,x+13,y+20);line(c,x+13,y+10,x+7,y+20);}c.restore();}
function drawSprite(c,id,x,y,scale=1){const rows=DATA.sprites[id%50];c.fillStyle='#f6f3df';if(scale===.5){for(let r=0;r<16;r++){const a=rows[r*2]>>>0,b=rows[r*2+1]>>>0;for(let col=0;col<16;col++){const mask=0xC0000000>>>(col*2);if((a&mask)||(b&mask))c.fillRect(x+col,y+r,1,1);}}return;}for(let r=0;r<32;r++){const bits=rows[r]>>>0;for(let col=0;col<32;col++)if((bits&(0x80000000>>>col))!==0)c.fillRect(x+col*scale,y+r*scale,scale,scale);}}
function drawGrowth(c,stage,x,y,sc=1,sleep=false){const bob=(ui.frame&1)?sc:0;c.save();c.fillStyle='#f6f3df';c.strokeStyle='#f6f3df';if(stage==='egg'){roundRect(c,x+4*sc,y+1*sc+bob,8*sc,14*sc,4*sc,true);c.fillStyle='#020303';c.fillRect(x+5*sc,y+4*sc+bob,2*sc,2*sc);c.fillRect(x+10*sc,y+8*sc+bob,2*sc,2*sc);c.fillRect(x+6*sc,y+12*sc+bob,3*sc,sc);c.restore();return;}if(stage==='baby'){roundRect(c,x+3*sc,y+5*sc+bob,10*sc,8*sc,4*sc,true);c.fillRect(x+5*sc,y+3*sc+bob,2*sc,3*sc);c.fillRect(x+9*sc,y+2*sc+bob,2*sc,4*sc);c.fillRect(x+4*sc,y+12*sc+bob,3*sc,2*sc);c.fillRect(x+9*sc,y+12*sc+bob,3*sc,2*sc);}else if(stage==='child'){roundRect(c,x+2*sc,y+4*sc+bob,12*sc,10*sc,4*sc,true);if((state.pet.temperament&1)===0){c.beginPath();c.moveTo(x+3*sc,y+5*sc+bob);c.lineTo(x+4*sc,y);c.lineTo(x+7*sc,y+5*sc+bob);c.fill();c.beginPath();c.moveTo(x+9*sc,y+5*sc+bob);c.lineTo(x+12*sc,y);c.lineTo(x+13*sc,y+5*sc+bob);c.fill();}else{c.fillRect(x+3*sc,y+1*sc+bob,3*sc,4*sc);c.fillRect(x+10*sc,y+1*sc+bob,3*sc,4*sc);}c.fillRect(x+3*sc,y+13*sc+bob,3*sc,2*sc);c.fillRect(x+10*sc,y+13*sc+bob,3*sc,2*sc);}else{roundRect(c,x+1*sc,y+3*sc+bob,14*sc,11*sc,4*sc,true);c.beginPath();c.moveTo(x+2*sc,y+5*sc+bob);c.lineTo(x+4*sc,y);c.lineTo(x+7*sc,y+4*sc+bob);c.fill();c.beginPath();c.moveTo(x+9*sc,y+4*sc+bob);c.lineTo(x+12*sc,y);c.lineTo(x+14*sc,y+5*sc+bob);c.fill();c.fillRect(x,y+8*sc+bob,3*sc,2*sc);c.fillRect(x+13*sc,y+8*sc+bob,3*sc,2*sc);c.fillRect(x+3*sc,y+13*sc+bob,3*sc,3*sc);c.fillRect(x+10*sc,y+13*sc+bob,3*sc,3*sc);}c.fillStyle='#020303';const ey=y+8*sc+bob;if(sleep){line(c,x+5*sc,ey,x+7*sc,ey);line(c,x+9*sc,ey,x+11*sc,ey);}else{c.fillRect(x+5*sc,ey-sc,sc,2*sc);c.fillRect(x+10*sc,ey-sc,sc,2*sc);}line(c,x+7*sc,ey+3*sc,x+9*sc,ey+3*sc);c.restore();}
function drawPet(c,x,y,small=false){const p=state.pet;if(p.stage==='egg'){drawGrowth(c,'egg',x,y,2,false);return;}if(['baby','child','teen'].includes(p.stage)){drawGrowth(c,p.stage,x,y,small?1:2,p.sleeping);return;}drawSprite(c,p.species,x,y,small?.5:1);if(p.stage==='elder'){line(c,x+27,y+19,x+29,y+30);line(c,x+29,y+30,x+31,y+30);}if(p.outfit){drawHat(c,x,y,p.outfit,small);}}
function drawHat(c,x,y,id,small=false){c.save();c.strokeStyle='#f6f3df';c.fillStyle='#f6f3df';const s=small?.5:1,xx=x+(small?1:3),yy=y-(small?2:5);switch(id%5){case 0:line(c,xx,yy+4,xx+24*s,yy+4);c.beginPath();c.arc(xx+12*s,yy+4,8*s,Math.PI,0);c.stroke();break;case 1:c.beginPath();c.moveTo(xx+4,yy+5);c.lineTo(xx+12,yy-2);c.lineTo(xx+20,yy+5);c.stroke();break;case 2:c.strokeRect(xx+5,yy,16*s,6*s);break;case 3:c.beginPath();c.arc(xx+12,yy+2,9,Math.PI,0);c.stroke();break;default:line(c,xx+2,yy+5,xx+22,yy+5);c.fillRect(xx+9,yy-2,6,7);}c.restore();}
function drawWindow(c,x,y,w=22,h=15){c.strokeRect(x,y,w,h);line(c,x+w/2,y,x+w/2,y+h);line(c,x,y+h/2,x+w,y+h/2);const hr=new Date().getHours(),night=hr>=19||hr<7;if(night){c.fillRect(x+4,y+3,1,1);c.fillRect(x+16,y+4,1,1);c.beginPath();c.arc(x+7,y+5,3,0,Math.PI*2);c.stroke();}else{c.beginPath();c.arc(x+5,y+4,3,0,Math.PI*2);c.stroke();}}
function roomShell(c){c.fillRect(0,8,128,3);c.fillRect(0,8,3,47);c.fillRect(125,8,3,47);c.fillRect(0,52,128,3);line(c,3,14,125,14);drawWindow(c,101,17);}
function drawPoop(c,x,y){c.fillRect(x,y+4,9,3);c.fillRect(x+2,y+2,6,2);c.fillRect(x+4,y,3,2);}
function drawPetRoom(){clear(mctx,128,64);roomShell(mctx);mctx.strokeRect(7,38,30,13);mctx.strokeRect(94,35,25,16);mctx.strokeRect(8,17,18,12);mctx.strokeRect(44,44,42,7);const act=currentActivity();if(act==='school'||act==='work'){mctx.strokeRect(34,20,60,28);text(mctx,act==='school'?'AT SCHOOL':'AT WORK',64,25,7,'center');text(mctx,'CARE COVERED',64,36,6,'center');return;}if(act==='sleep'){drawPet(mctx,48,22,false);text(mctx,'Z',88,20,10);text(mctx,'z',98,14,7);return;}const solo=!state.pet.spouse&&!state.pet.children.length;drawPet(mctx,solo?48:39,20,false);if(state.pet.companion){mctx.beginPath();mctx.arc(28,47,5,0,Math.PI*2);mctx.stroke();}if(state.pet.spouse)drawSprite(mctx,state.pet.spouse.species,78,28,.5);if(state.pet.children.length)drawGrowth(mctx,'child',102,34,1,false);for(let i=0;i<state.pet.poop;i++)drawPoop(mctx,8+i*13,47);}
function drawKitchen(){clear(mctx,128,64);roomShell(mctx);mctx.strokeRect(5,29,34,22);mctx.strokeRect(89,29,33,22);mctx.strokeRect(10,34,12,12);mctx.strokeRect(97,35,18,11);mctx.strokeRect(46,42,34,9);drawPet(mctx,49,19,false);}
function drawGarden(){clear(mctx,128,64);mctx.fillRect(0,8,128,3);drawWindow(mctx,101,15);line(mctx,0,53,127,53);for(let i=0;i<4;i++){const x=5+i*30;mctx.strokeRect(x,38,24,14);const p=state.garden.plots[i];if(p)drawPlant(mctx,x+12,50,p.growth,p.health);}drawPet(mctx,48,17,false);}
function drawPlant(c,x,y,growth=0,health=100){c.strokeStyle=health<30?'#f6f3df':'#f6f3df';line(c,x,y,x,y-Math.max(2,Math.floor(growth/10)));if(growth>20){line(c,x,y-3,x-4,y-6);line(c,x,y-5,x+4,y-8);}if(growth>60){c.beginPath();c.arc(x,y-11,3,0,Math.PI*2);c.stroke();}}
function drawAquarium(){clear(mctx,128,64);mctx.strokeRect(4,13,120,41);line(mctx,5,20,123,20);line(mctx,5,49,123,49);for(let i=0;i<state.aquarium.fish.length;i++)drawFish(mctx,13+(i*17)%100,29+(i%2)*11,i);drawPet(mctx,48,19,false);}
function drawFish(c,x,y,i){c.beginPath();c.ellipse(x,y,5,3,0,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(x-5,y);c.lineTo(x-9,y-4);c.lineTo(x-9,y+4);c.closePath();c.stroke();c.fillRect(x+2,y-1,1,1);}
function drawFamilyRoom(){clear(mctx,128,64);roomShell(mctx);mctx.strokeRect(7,39,25,12);mctx.strokeRect(97,39,23,12);drawPet(mctx,30,20,false);if(state.pet.spouse)drawSprite(mctx,state.pet.spouse.species,72,28,.5);if(state.pet.children.length)drawGrowth(mctx,'child',102,34,1,false);}
function drawHome(){const room=DATA.rooms[ui.roomIndex%DATA.rooms.length];if(room==='Kitchen')drawKitchen();else if(room==='Garden'||room==='Plant Room')drawGarden();else if(room==='Aquarium')drawAquarium();else if(room==='Family Room')drawFamilyRoom();else drawPetRoom();drawHeader(room);drawFooter('D0 ROOM','D1 ENTER','D2 ROOM');}
function drawCity(){clear(mctx,128,64);const place=DATA.city[ui.cityIndex%DATA.city.length];if(place==='Park'){line(mctx,0,51,127,51);for(let i=0;i<3;i++){const x=14+i*40;line(mctx,x,47,x,25);mctx.beginPath();mctx.arc(x,21,9,0,Math.PI*2);mctx.stroke();}}else if(place==='Cafe'){mctx.strokeRect(8,20,112,32);mctx.strokeRect(20,30,30,22);mctx.strokeRect(65,29,42,23);line(mctx,8,20,64,11);line(mctx,120,20,64,11);}else{const heights=[27,35,24,32];for(let i=0;i<4;i++){const x=4+i*31,y=52-heights[i];mctx.strokeRect(x,y,27,heights[i]);for(let yy=y+5;yy<50;yy+=8)for(let xx=x+5;xx<x+23;xx+=8)mctx.strokeRect(xx,yy,3,3);}line(mctx,0,52,127,52);}drawPet(mctx,48,20,false);drawHeader(place);drawFooter('D0 PLACE','D1 ENTER','D2 PLACE');}
function drawHeader(title){mctx.fillStyle='#020303';mctx.fillRect(0,0,128,8);mctx.strokeStyle='#f6f3df';line(mctx,0,8,127,8);text(mctx,title.slice(0,14).toUpperCase(),2,0,7);text(mctx,new Intl.DateTimeFormat([],{hour:'numeric',minute:'2-digit'}).format(new Date()),126,0,6,'right');}
function drawFooter(l,c,r){mctx.fillStyle='#020303';mctx.fillRect(0,55,128,9);mctx.strokeStyle='#f6f3df';line(mctx,0,55,127,55);text(mctx,l,1,57,5);text(mctx,c,64,57,5,'center');text(mctx,r,127,57,5,'right');}
function icon(c,id,x,y){c.save();c.strokeStyle='#f6f3df';c.fillStyle='#f6f3df';const n=id%10;if(n===0){c.beginPath();c.arc(x+12,y+12,9,0,Math.PI*2);c.stroke();line(c,x+5,y+12,x+19,y+12);}else if(n===1){roundRect(c,x+2,y+6,21,14,4,false);line(c,x+7,y+13,x+12,y+13);line(c,x+9,y+10,x+9,y+16);c.fillRect(x+17,y+10,2,2);c.fillRect(x+19,y+14,2,2);}else if(n===2){roundRect(c,x+2,y+4,21,15,4,false);line(c,x+8,y+19,x+4,y+23);line(c,x+7,y+11,x+18,y+11);}else if(n===3){c.beginPath();c.moveTo(x+2,y+11);c.lineTo(x+12,y+2);c.lineTo(x+23,y+11);c.stroke();c.strokeRect(x+5,y+11,15,12);}else if(n===4){c.strokeRect(x+3,y+5,20,17);c.fillRect(x+7,y+14,3,5);c.fillRect(x+13,y+10,3,9);c.fillRect(x+19,y+7,3,12);}else if(n===5){c.beginPath();c.arc(x+12,y+12,10,0,Math.PI*2);c.stroke();line(c,x+12,y+2,x+12,y+22);line(c,x+2,y+12,x+22,y+12);}else if(n===6){line(c,x+8,y+3,x+8,y+18);line(c,x+8,y+3,x+20,y+6);c.beginPath();c.arc(x+5,y+19,4,0,Math.PI*2);c.fill();}else if(n===7){c.strokeRect(x+3,y+7,20,15);c.strokeRect(x+8,y+3,10,4);line(c,x+3,y+13,x+23,y+13);}else if(n===8){mctx.strokeRect(x+3,y+3,20,20);mctx.strokeRect(x+7,y+7,5,5);mctx.strokeRect(x+15,y+15,5,5);}else{c.beginPath();c.arc(x+12,y+12,9,0,Math.PI*2);c.stroke();for(let a=0;a<8;a++){const t=a*Math.PI/4;line(c,x+12+Math.cos(t)*10,y+12+Math.sin(t)*10,x+12+Math.cos(t)*13,y+12+Math.sin(t)*13);}}c.restore();}
const MENU=[
 ['Food','Meals and snacks','food',0],['Games','Arcade and stage games','games',1],['Clean','Bath and room care','clean',2],['Medicine','Treat sickness','medicine',3],['Talk','Parent and life dialogue','talk',2],['Love','Praise and bond','love',0],['Walk','Outdoor activity','walk',5],['Train','Build physical skill','train',1],['Study','Build intelligence','study',4],['Garden','Grow food crops','garden',3],['Plant Room','Care for houseplants','plants',3],['Aquarium','Fish care','aquarium',5],['Music Disc','Imported MP3 library','music',6],['Stats','Needs and schedule','stats',4],['Shop','Hats, rooms and toys','shop',7],['Explore','Expeditions and crafting','explore',5],['Cook','Prepare recipes','cook',0],['Job','Careers and work','job',7],['Room','Decor and themes','room',3],['Family','Spouse, children, legacy','family',2],['Album','Past Tamas and collections','album',8],['Living World','Events, memories and goals','life',8],['Paradise Lab','Planet, fields and travel','paradise',5],['Settings','Save, accessibility, reset','settings',9]
];
function itemUnlocked(item){const st=state.pet.stage;if(st==='egg')return false;if(['food','clean','medicine','talk','love','stats','settings','music','games'].includes(item[2]))return st!=='egg';if(['walk','train','garden','plants','aquarium','shop','room'].includes(item[2]))return ['child','teen','adult','elder'].includes(st);if(['study','explore','life','paradise'].includes(item[2]))return ['teen','adult','elder','child'].includes(st);if(['job','family','cook'].includes(item[2]))return ['adult','elder'].includes(st);return true;}
function drawMenu(){clear(mctx,128,64);const item=MENU[ui.menuIndex%MENU.length];drawHeader('MAIN MENU');roundRect(mctx,4,13,38,36,5,false);icon(mctx,item[3],10,20);roundRect(mctx,46,13,78,36,5,false);text(mctx,item[0].toUpperCase().slice(0,12),51,17,7);text(mctx,item[1].slice(0,18),51,29,5);text(mctx,itemUnlocked(item)?'READY':state.pet.stage==='egg'?'AFTER HATCH':'LOCKED',51,40,6);text(mctx,`${ui.menuIndex+1}/${MENU.length}`,119,46,5,'right');drawFooter('D0 PREV','D1 OPEN','D2 NEXT');}
function drawEggSelect(){clear(mctx,128,64);drawHeader('CHOOSE EGG');for(let i=0;i<4;i++)drawEgg(mctx,8+i*30,28,ui.eggChoices[i],i===ui.eggIndex);const names=['Soft stripe egg','Spotted wild egg','Smart cross egg','Mystery cute egg','Tall stripe egg','Pointy rare egg','Plus sign egg','Tri mark egg','Round badge egg','Cross mark egg'];text(mctx,names[ui.eggChoices[ui.eggIndex]%10].slice(0,20),64,48,6,'center');drawFooter('D0 PREV','D1 CHOOSE','D2 NEXT');}
function drawMusicScene(){clear(mctx,128,64);roomShell(mctx);drawPet(mctx,48,19,false);mctx.beginPath();mctx.arc(49,31,6,Math.PI/2,Math.PI*1.5);mctx.stroke();mctx.beginPath();mctx.arc(79,31,6,-Math.PI/2,Math.PI/2);mctx.stroke();for(let i=0;i<3;i++){const x=91+i*9,y=17+(i%2)*9;line(mctx,x,y,x,y+8);line(mctx,x,y,x+5,y+2);mctx.beginPath();mctx.arc(x-2,y+9,2,0,Math.PI*2);mctx.fill();}drawHeader('MUSIC DISC');drawFooter('D0 LAST','D1 PAUSE','D2 NEXT');}
function renderMain(){if(ui.screen==='eggSelect'){drawEggSelect();return;}if(ui.screen==='menu'){drawMenu();return;}if(currentTrack>=0){drawMusicScene();return;}if(ui.world===0){drawPetRoom();drawHeader(state.pet.stage==='egg'?'EGG ROOM':'TAMAGOTCHI');drawFooter('D0 MENU','D1 OPEN','D2 MENU');}else if(ui.world===1)drawHome();else drawCity();}
function urgency(v){return v<=2?2:v<=4?1:0;}
function drawStatus(){clear(sctx,128,32);const p=state.pet,act=currentActivity();if(currentTrack>=0){const t=tracks[currentTrack];text(sctx,t?.artist?.slice(0,20)||'Unknown Artist',0,0,7);text(sctx,t?.title?.slice(0,20)||'Unknown Song',0,9,7);line(sctx,0,18,127,18);text(sctx,audio.paused?'PAUSED':'PLAY',0,22,7);text(sctx,`VOL ${Math.round(state.music.volume*100)}`,127,22,7,'right');return;}if(p.stage==='egg'){text(sctx,'EGG IS RESTING',64,2,8,'center');text(sctx,'HATCHES AFTER 5 MIN',64,14,6,'center');return;}if(['school','work','sleep','sitter'].includes(act)){text(sctx,ACTIVITY_LABEL[act],64,1,8,'center');text(sctx,act==='sleep'?'ENERGY RECOVERING':'NEEDS ARE COVERED',64,12,6,'center');const sc=schedule(p.stage);text(sctx,act==='sleep'?`WAKE ${hourLabel(sc.wake)}`:act==='school'?'BACK 3:00 PM':act==='work'?'BACK 5:00 PM':'CARE ACTIVE',64,22,6,'center');return;}const stats=[['FD',p.stats.full],['FN',p.stats.happy],['EN',p.stats.energy],['CL',p.stats.clean],['HP',p.stats.health],['PP',Math.max(0,10-p.poop*3)]];stats.forEach(([lab,v],i)=>{const x=(i%3)*43,y=Math.floor(i/3)*16,u=urgency(v),show=u===0||(u===1?ui.frame%4<2:ui.frame%2===0);if(!show)return;text(sctx,lab,x,y,6);text(sctx,Math.round(v),x+34,y,6,'right');sctx.strokeRect(x,y+8,38,5);sctx.fillRect(x+1,y+9,Math.round(36*clamp(v)/10),3);});}
function hourLabel(h){const ap=h>=12?'PM':'AM',n=h%12||12;return`${n}:00 ${ap}`;}
function setDialMode(){const slider=$('#worldSlider'),labels=$$('.dial-labels span');if(currentTrack>=0){slider.min=0;slider.max=100;slider.step=1;slider.value=Math.round(state.music.volume*100);labels[0].textContent='MIN';labels[1].textContent='VOLUME';labels[2].textContent='MAX';}else{slider.min=0;slider.max=2;slider.step=1;slider.value=ui.world;labels[0].textContent='TAMA';labels[1].textContent='HOME';labels[2].textContent='CITY';}}function render(){renderMain();drawStatus();setDialMode();}

// ---------- actions and panels ----------
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),2200);}
function showSheet(title,html,eyebrow='MENU'){ui.screenBeforeSheet=ui.screen;$('#sheetEyebrow').textContent=eyebrow;$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=html;$('#sheet').classList.remove('hidden');}
function closeSheet(){if(game)stopGame(false);$('#sheet').classList.add('hidden');}
function actionButton(label,desc,id,disabled=false){return`<button class="pixel-action" data-action="${id}" ${disabled?'disabled':''}><strong>${label}</strong><small>${desc}</small></button>`;}
function chooseEgg(){const species=ui.eggChoices[ui.eggIndex];const entered=prompt('Name your Tamagotchi (up to 8 characters):',state.pet.name||'Tama');if(entered)state.pet.name=entered.trim().slice(0,8)||'Tama';state.pet.eggType=species;state.pet.species=species;state.pet.birthCode=rand(65536);state.pet.temperament=species%8;state.pet.personality=species%8;state.pet.ageTicks=0;state.pet.stage='egg';ui.screen='scene';addMemory(`A ${DATA.species[species]} egg was chosen.`);queueSave();toast('New egg — hatches in 5 minutes');render();}
function feedPanel(){showSheet('Food',`<div class="pixel-grid">${DATA.foods.map((f,i)=>actionButton(f.name,`Full +${f.full} · Happy +${f.happy}`,`feed:${i}`,state.inventory.meals<=0&&i<3)).join('')}</div><div class="pixel-panel"><p>Meals ${state.inventory.meals} · Snacks ${state.inventory.snacks}</p></div>`,'CARE');}
function feed(i){if(state.pet.stage==='egg'){toast('The egg cannot eat yet.');return;}const f=DATA.foods[i];if(i<3){if(state.inventory.meals<=0){toast('No meals left.');return;}state.inventory.meals--;}else{if(state.inventory.snacks<=0){toast('No snacks left.');return;}state.inventory.snacks--;}addStat('full',f.full);addStat('happy',f.happy);state.pet.favoriteFood=i;changeBond(1);addMemory(`${state.pet.name} ate ${f.name}.`);beep(520,.07);queueSave();feedPanel();render();}
function cleanAction(){if(state.pet.stage==='egg')return toast('The egg is clean.');const cleaned=state.pet.poop;state.paradise.biofuel+=cleaned*6;state.pet.poop=0;state.pet.stats.clean=10;state.pet.condition=Math.max(0,state.pet.condition-1);changeBond(1);addMemory(`${state.pet.name} had a bath.`);beep(680,.08);queueSave();render();toast('All clean!');}
function medicinePanel(){showSheet('Medicine',`<div class="pixel-panel"><h3>Health ${state.pet.stats.health}/10</h3><p>${state.pet.sick||state.pet.condition?'Symptoms need treatment.':'No serious symptoms.'}</p></div><div class="pixel-grid">${actionButton('General Medicine',`Stock ${state.inventory.medicine}`,'medicine:general')}${actionButton('Rest and Fluids','Gentle recovery plan','medicine:rest')}${actionButton('Cell Lab','Inspect illness cells','paradise:cell')}</div>`,'HEALTH');}
function medicine(kind){if(kind==='general'){if(state.inventory.medicine<=0)return toast('No medicine left.');state.inventory.medicine--;state.pet.sick=false;state.pet.condition=0;addStat('health',3);}else{addStat('health',1);addStat('energy',1);}changeTrust(1);queueSave();medicinePanel();render();}
function statsPanel(){const p=state.pet,act=currentActivity(),s=schedule(p.stage);showSheet('Status',`<div class="pixel-panel"><h3>${p.name} · ${p.stage.toUpperCase()}</h3><p>${DATA.species[p.species]} · Generation ${p.generation} · ${p.career||'No career'}</p></div><div class="pixel-grid">${Object.entries(p.stats).map(([k,v])=>`<div class="pixel-panel"><b>${k.toUpperCase()} ${v}/10</b><div class="meter"><i style="width:${v*10}%"></i></div></div>`).join('')}</div><div class="pixel-panel"><p>Bond ${p.ownerBond}/100 · Trust ${p.ownerTrust}/100 · Care mistakes ${p.careMistakes}</p><p>Activity: ${ACTIVITY_LABEL[act]} · Bed ${hourLabel(s.bed)} · Wake ${hourLabel(s.wake)}</p><p>Age: ${Math.floor(p.ageTicks/TICKS_PER_DAY)} days · Coins ${Math.floor(p.coins)}</p></div>`,'STATUS');}
function talkPanel(){showSheet('Talk',`<div class="pixel-grid">${actionButton('Parent Check-In','Age-matched conversation','talk:parent')}${actionButton('Growing Together','Long-form family topic','talk:growing',state.pet.stage==='baby'||state.pet.stage==='egg')}${actionButton('Current Life Event','Respond to today’s event','talk:event')}${actionButton('Memories',`${state.narrative.memories.length} recorded`,'talk:memories')}</div>`,'BOND');}
function showDialogue({type,title,text:body,choices=[],replies=[],onChoice}){$('#dialogueType').textContent=type;$('#dialogueTitle').textContent=title;$('#dialogueText').textContent=body;$('#dialogueChoices').innerHTML='';$('#dialogueContinue').classList.add('hidden');drawDialoguePet();choices.forEach((ch,i)=>{const b=document.createElement('button');b.className='pixel-action';b.textContent=ch;b.onclick=()=>{onChoice?.(i);$('#dialogueChoices').innerHTML='';$('#dialogueText').textContent=replies[i]||'Your Tamagotchi remembers your answer.';$('#dialogueContinue').classList.remove('hidden');};$('#dialogueChoices').appendChild(b);});$('#dialogue').classList.remove('hidden');}
function drawDialoguePet(){clear(dctx,48,48);if(state.pet.stage==='adult'||state.pet.stage==='elder')drawSprite(dctx,state.pet.species,8,8,1);else drawGrowth(dctx,state.pet.stage,8,8,2,false);}
function parentTalk(){if(state.pet.stage==='egg')return toast('The egg is quiet.');const topics=DATA.parentTopics.filter(t=>t.stage===state.pet.stage);if(!topics.length&&state.pet.stage==='baby'){const syll=['ba','ma','da','goo','mimi','baba'],cue=['points at you','wiggles happily','looks worried','reaches up','copies your sound'];showDialogue({type:'BABY BABBLE',title:'What do you think?',text:`${pick(syll)}-${pick(syll)}! ${state.pet.name} ${pick(cue)}.`,choices:['Babble back','Cuddle and listen','Wait quietly'],replies:['The baby squeals and copies you.','The baby relaxes in your arms.','The baby watches and tries again.'],onChoice:i=>{changeBond(i<2?2:0);changeTrust(i===1?2:0);state.narrative.openness+=i<2?1:0;}});return;}const topic=pick(topics);showDialogue({type:`${state.pet.stage.toUpperCase()} TALK`,title:topic.question,text:topic.prompt,choices:topic.choices,replies:topic.replies,onChoice:i=>{const positive=i<2;changeBond(positive?2:-1);changeTrust(positive?2:-2);state.narrative.openness=clamp(state.narrative.openness+(positive?2:-2),0,100);state.narrative.history.unshift({kind:'parent',topic:topic.id,choice:i,at:now()});addMemory(`${topic.prompt} You answered: ${topic.choices[i]}.`);queueSave();}});}
const GT_RESPONSES=[['Listen first','Make a plan','Avoid the subject'],['Keep the promise','Reschedule honestly','Forget it'],['Apologize clearly','Offer repair','Defend yourself'],['Ask what feels safe','Offer quiet company','Ignore the boundary'],['Praise effort','Practice together','Compare them']];
function growingTalk(){if(['egg','baby'].includes(state.pet.stage))return toast('Growing Together unlocks at Child.');const fi=rand(DATA.growingTogether.features.length),lead=pick(DATA.growingTogether.leads),scenario=pick(DATA.growingTogether.scenarios[fi]),end=pick(DATA.growingTogether.endings),choices=GT_RESPONSES[fi%GT_RESPONSES.length];showDialogue({type:'GROWING TOGETHER',title:DATA.growingTogether.features[fi],text:`${lead} ${scenario} ${end}`,choices,replies:['Your Tamagotchi feels heard.','You agree on a practical next step.','The concern remains unresolved.'],onChoice:i=>{changeBond(i<2?2:-2);changeTrust(i<2?2:-2);state.narrative.history.unshift({kind:'growing',feature:fi,choice:i,at:now()});addMemory(`${DATA.growingTogether.features[fi]}: ${scenario}`);queueSave();}});}
function eventValid(e){const cat=e.category.toLowerCase(),st=state.pet.stage;if(cat.includes('baby'))return st==='baby';if(cat.includes('child'))return st==='child';if(cat.includes('teen'))return st==='teen';if(cat.includes('adult'))return st==='adult';if(cat.includes('elder'))return st==='elder';if(cat.includes('spouse'))return!!state.pet.spouse;if(cat.includes('companion'))return!!state.pet.companion;if(cat.includes('garden'))return state.garden.plots.some(Boolean);return st!=='egg';}
function maybeLifeEvent(){const day=Math.floor(state.pet.ageTicks/TICKS_PER_DAY);if(day===state.pet.lastEventDay||state.pet.stage==='egg')return;if(state.pet.ageTicks%TICKS_PER_DAY!==0)return;state.pet.lastEventDay=day;const pool=DATA.lifeEvents.filter(eventValid);if(pool.length){state.pendingEvent=pick(pool);state.notifications.log.unshift(`Life event: ${state.pendingEvent.title}`);}}
function lifeEvent(){let e=state.pendingEvent;if(!e){const pool=DATA.lifeEvents.filter(eventValid);e=pick(pool);}showDialogue({type:e.category,title:e.title,text:e.prompt,choices:e.choices,replies:['Your choice becomes part of the family story.','The other path changes what happens next.'],onChoice:i=>{changeBond(i===0?1:0);state.city.reputation[i===0?'helpful':'adventurous']++;addMemory(`${e.title}: ${e.choices[i]}`);state.pendingEvent=null;queueSave();}});}
function memoriesPanel(){showSheet('Memories',state.narrative.memories.length?state.narrative.memories.map(m=>`<div class="pixel-panel"><p>${m.text}</p><small>${new Date(m.at).toLocaleString()}</small></div>`).join(''):'<div class="pixel-panel"><p>No memories yet.</p></div>','DIARY');}
function loveAction(){if(state.pet.stage==='egg')return toast('You sit beside the egg.');addStat('happy',2);changeBond(3);changeTrust(1);state.pet.stats.discipline=clamp(state.pet.stats.discipline+1);beep(760,.09);toast(`${state.pet.name} feels loved.`);addMemory('You spent focused time together.');queueSave();render();}
function gardenPanel(indoor=false){const arr=indoor?state.garden.indoor:state.garden.plots;showSheet(indoor?'Plant Room':'Garden',arr.map((p,i)=>`<div class="pixel-panel"><div class="row"><b>${indoor?'Pot':'Plot'} ${i+1}</b><span>${p?p.species:'Empty'}</span></div>${p?`<p>Growth ${Math.round(p.growth)} · Water ${Math.round(p.water)} · Health ${Math.round(p.health)}</p>`:'<p>Nothing planted.</p>'}<div class="pixel-grid"><button class="pixel-action" data-garden="plant:${indoor?1:0}:${i}">PLANT</button><button class="pixel-action" data-garden="water:${indoor?1:0}:${i}">WATER</button><button class="pixel-action" data-garden="harvest:${indoor?1:0}:${i}">HARVEST</button></div></div>`).join(''),'BOTANY');$$('[data-garden]').forEach(b=>b.onclick=()=>{const[a,inside,idx]=b.dataset.garden.split(':');gardenAction(a,+inside,+idx);});}
function gardenAction(action,inside,index){const arr=inside?state.garden.indoor:state.garden.plots,p=arr[index];if(action==='plant'){if(state.inventory.seeds<=0)return toast('No seeds.');state.inventory.seeds--;const names=inside?DATA.indoorPlants:DATA.crops;arr[index]={species:pick(names),growth:0,water:80,health:100};}else if(action==='water'){if(!p)return toast('Nothing planted.');p.water=100;p.health=clamp(p.health+5,0,100);}else{if(!p||p.growth<100)return toast('Not ready.');state.inventory[p.species==='Basil'?'herbs':'veg']=(state.inventory[p.species==='Basil'?'herbs':'veg']||0)+2;state.garden.harvests++;if(!state.collections.plants.includes(p.species))state.collections.plants.push(p.species);arr[index]=null;markAchievement('First Harvest');}queueSave();gardenPanel(!!inside);render();}
function aquariumPanel(){showSheet('Aquarium',`<div class="pixel-panel"><p>Clean ${Math.round(state.aquarium.clean)} · Quality ${Math.round(state.aquarium.quality)}</p></div>${state.aquarium.fish.map((f,i)=>`<div class="pixel-panel"><b>${f.name}</b><p>${f.species} · Hunger ${Math.round(f.hunger)} · Mood ${Math.round(f.mood)}</p></div>`).join('')||'<div class="pixel-panel"><p>No fish yet.</p></div>'}<div class="pixel-grid">${actionButton('Feed Fish','Raise hunger','aquarium:feed')}${actionButton('Clean Tank','Restore water','aquarium:clean')}${actionButton('Buy Fish','20 coins','aquarium:buy')}</div>`,'AQUARIUM');}
function aquariumAction(a){if(a==='feed')for(const f of state.aquarium.fish)f.hunger=clamp(f.hunger+35,0,100);else if(a==='clean'){state.aquarium.clean=100;state.aquarium.quality=100;}else{if(state.pet.coins<20)return toast('Need 20 coins.');state.pet.coins-=20;const species=pick(DATA.fish);state.aquarium.fish.push({name:species.slice(0,6),species,hunger:90,mood:80});if(!state.collections.fish.includes(species))state.collections.fish.push(species);}queueSave();aquariumPanel();render();}
function cookPanel(){showSheet('Kitchen',DATA.recipes.map((r,i)=>`<div class="pixel-panel"><b>${r.name}</b><p>${Object.entries(r.needs).map(([k,v])=>`${k} ${v}`).join(' · ')}</p><button class="pixel-action" data-recipe="${i}">COOK</button></div>`).join(''),'COOK');$$('[data-recipe]').forEach(b=>b.onclick=()=>cook(+b.dataset.recipe));}
function cook(i){const r=DATA.recipes[i];for(const[k,v]of Object.entries(r.needs))if((state.inventory[k]||0)<v)return toast(`Need more ${k}.`);for(const[k,v]of Object.entries(r.needs))state.inventory[k]-=v;addStat('full',r.full||0);addStat('happy',r.happy||0);addStat('health',r.health||0);addStat('clean',r.clean||0);state.pet.skills.smart++;addMemory(`Cooked ${r.name}.`);queueSave();cookPanel();}
function familyPanel(){const p=state.pet;showSheet('Family',`<div class="pixel-panel"><p>Spouse: ${p.spouse?p.spouse.name:'None'} · Children: ${p.children.length} · Companion: ${p.companion||'None'}</p></div><div class="pixel-grid">${actionButton(p.spouse?'Spend Time':'Choose Partner','Adult relationship','family:spouse',!['adult','elder'].includes(p.stage))}${actionButton('Have Child','Inheritance and generations','family:child',!p.spouse)}${actionButton(p.companion?'Train Companion':'Adopt Companion','Helper pet','family:companion')}${actionButton('Next Generation','Choose an heir','family:next',!p.children.length)}</div>`,'FAMILY');}
function familyAction(a){const p=state.pet;if(a==='spouse'){if(p.spouse){changeBond(2);toast('You spend time together.');}else{const options=Object.entries(state.city.relationships).filter(([,r])=>r.bond>=50);if(!options.length)return toast('Build a neighbor bond first.');const [name]=pick(options);p.spouse={name,species:rand(50),bond:60};addMemory(`${name} moved into the family home.`);}}else if(a==='child'){if(p.children.length>=3)return toast('Family is full.');p.children.push({name:`Child${p.children.length+1}`,species:(p.species+(p.spouse?.species||0)+rand(5))%50,bond:50,talent:rand(4)});addMemory('A new child joined the family.');}else if(a==='companion'){if(!p.companion)p.companion=pick(DATA.companions);else{changeBond(1);addStat('happy',1);}}else if(a==='next'){nextGeneration();return;}queueSave();familyPanel();render();}
function archivePet(){const p=state.pet;p.album.unshift({name:p.name,species:p.species,age:Math.floor(p.ageTicks/TICKS_PER_DAY),bond:p.ownerBond,generation:p.generation});p.album=p.album.slice(0,8);}
function nextGeneration(){const p=state.pet;if(!p.children.length)return;archivePet();const child=p.children[0],gen=p.generation+1,album=p.album;state.pet={...baseState().pet,name:child.name,species:child.species,eggType:child.species,generation:gen,album};state.pet.stage='egg';state.pet.ageTicks=0;ui.screen='scene';addMemory(`Generation ${gen} began as an egg.`);closeSheet();queueSave();render();}
function careerPanel(){showSheet('Career',`<div class="pixel-panel"><p>Current: ${state.pet.career||'None'} · XP ${Math.floor(state.pet.careerXP)}</p></div><div class="pixel-grid">${DATA.careers.map((c,i)=>actionButton(c,`Skill path ${i+1}`,`career:${i}`)).join('')}</div>`,'WORK');}
function chooseCareer(i){state.pet.career=DATA.careers[i];state.pet.jobRank=1;addMemory(`${state.pet.name} began a ${state.pet.career} career.`);queueSave();careerPanel();}
function neighborPanel(){showSheet('Neighbors',DATA.neighbors.map(n=>{const r=state.city.relationships[n];return`<div class="pixel-panel"><div class="row"><b>${n}</b><span>Bond ${r.bond}</span></div><button class="pixel-action" data-neighbor="${n}">VISIT</button></div>`}).join(''),'CITY');$$('[data-neighbor]').forEach(b=>b.onclick=()=>{const r=state.city.relationships[b.dataset.neighbor];r.met=true;r.bond=clamp(r.bond+5,0,100);state.pet.ownerBond=clamp(state.pet.ownerBond+1,0,100);queueSave();neighborPanel();});}
function shopPanel(){showSheet('Shop',`<div class="pixel-panel"><p>Coins ${Math.floor(state.pet.coins)}</p></div><div class="pixel-grid">${actionButton('Meals x3','6 coins','shop:meals')}${actionButton('Snacks x3','8 coins','shop:snacks')}${actionButton('Medicine','8 coins','shop:medicine')}${actionButton('Seeds x3','5 coins','shop:seeds')}${actionButton('Fancy Hat','15 coins','shop:hat')}${actionButton('Room Theme','25 coins','shop:room')}</div>`,'SHOP');}
function shopAction(a){const costs={meals:6,snacks:8,medicine:8,seeds:5,hat:15,room:25},cost=costs[a];if(state.pet.coins<cost)return toast('Not enough coins.');state.pet.coins-=cost;if(a==='meals')state.inventory.meals+=3;else if(a==='snacks')state.inventory.snacks+=3;else if(a==='medicine')state.inventory.medicine++;else if(a==='seeds')state.inventory.seeds+=3;else if(a==='hat'){const id=rand(Math.max(1,DATA.outfits.length));if(!state.inventory.hats.includes(id))state.inventory.hats.push(id);state.pet.outfit=id;}else{const id=rand(10);if(!state.inventory.rooms.includes(id))state.inventory.rooms.push(id);state.pet.roomStyle=id;}queueSave();shopPanel();render();}
function collectionsPanel(){showSheet('Album & Collections',`<div class="pixel-panel"><p>Species ${state.collections.species.length}/50 · Fish ${state.collections.fish.length}/${DATA.fish.length} · Plants ${state.collections.plants.length}</p></div><div class="pixel-panel"><h3>Past Tamas</h3>${state.pet.album.map(a=>`<p>${a.name} · ${DATA.species[a.species]} · Gen ${a.generation} · ${a.age}d</p>`).join('')||'<p>None yet.</p>'}</div><div class="pixel-panel"><h3>Achievements</h3><p>${state.collections.achievements.join(' · ')||'None yet.'}</p></div>`,'ALBUM');}
function livingPanel(){showSheet('Living World',`<div class="pixel-grid">${actionButton('Life Event','240 contextual events','talk:event')}${actionButton('Parent Journal','Bond and development','life:journal')}${actionButton('Memories',`${state.narrative.memories.length} entries`,'talk:memories')}${actionButton('Goals','Daily and weekly progress','life:goals')}</div>`,'LIFE');}
function journalPanel(){const n=state.narrative;showSheet('Parent Journal',`<div class="pixel-grid">${['openness','confidence','empathy','honesty','resilience','responsibility','independence','security'].map(k=>`<div class="pixel-panel"><b>${k.toUpperCase()}</b><p>${Math.round(n[k])}/100</p></div>`).join('')}</div>`,'JOURNAL');}
function goalsPanel(){const age=Math.floor(state.pet.ageTicks/TICKS_PER_DAY);showSheet('Goals',`<div class="pixel-panel"><h3>Daily</h3><p>Feed once · Talk once · Play once</p></div><div class="pixel-panel"><h3>Legacy</h3><p>Current age ${age} days · Generation ${state.pet.generation} · Planet level ${state.paradise.level}</p></div>`,'GOALS');}
function paradisePanel(){showSheet('Paradise Lab',`<div class="pixel-panel"><p>Planet Lv ${state.paradise.level} · Research ${state.paradise.research} · Biofuel ${state.paradise.biofuel}</p><p>Fields: ${state.paradise.fields.join(', ')}</p></div><div class="pixel-grid">${actionButton('Planet Report','Progress and missions','paradise:report')}${actionButton('Egg Hunt','Once per day','paradise:egg')}${actionButton('Space Travel','Spend biofuel','paradise:space')}${actionButton('Cell Lab','Inspect and treat','paradise:cell')}${actionButton('Fields & Toys','Environment growth','paradise:fields')}${actionButton('Code Terminal','Enter 8 characters','paradise:code')}</div>`,'PARADISE');}
function checkParadiseMissions(){const p=state.pet,m=state.paradise.missions;if(p.stage==='child')m[0]=true;if(p.stage==='teen')m[1]=true;if(p.stage==='adult')m[2]=true;if(p.generation>1)m[3]=true;if(state.paradise.fields.length>=3)m[4]=true;}
function paradiseAction(a){if(a==='report'){showSheet('Planet Report',DATA.paradiseMissions.map((m,i)=>`<div class="pixel-panel"><p>${state.paradise.missions[i]?'[DONE]':'[ ]'} ${m}</p></div>`).join(''),'MISSIONS');}else if(a==='egg'){const day=new Date().toDateString();if(state.paradise.lastEggHuntDay===day)return toast('Egg hunt already used today.');state.paradise.lastEggHuntDay=day;state.inventory.berries+=2+rand(4);state.paradise.research+=8;addMemory('Completed a Paradise egg hunt.');toast('Egg hunt rewards found!');}else if(a==='space'){if(state.paradise.biofuel<12)return toast('Need 12 biofuel.');state.paradise.biofuel-=12;const dest=pick(['Sweet Planet','Relax Planet','Foodie Planet','Art Planet','Eco Planet','Music Planet']);if(!state.paradise.travel.includes(dest))state.paradise.travel.push(dest);state.inventory.materials+=2;addMemory(`Traveled to ${dest}.`);toast(dest);}else if(a==='cell'){if(state.pet.sick||state.pet.condition){state.pet.sick=false;state.pet.condition=Math.max(0,state.pet.condition-1);addStat('health',2);state.paradise.research+=3;toast('Diseased cells treated.');}else toast('Cells look healthy.');}else if(a==='fields'){if(state.paradise.level>=5&&state.paradise.fields.length<3)state.paradise.fields.push(state.paradise.fields.length===1?'Water':'Sky');toast(`Current field: ${state.paradise.currentField}`);}else{const code=prompt('Enter code');if(code){const c=code.toUpperCase();if(c==='PICO2026'){state.pet.coins+=20;state.paradise.research+=5;}else if(c==='GARDEN88'){state.inventory.seeds+=8;}else if(c==='STARLAB1'){state.paradise.research+=50;}else if(c==='AQUA2026'){state.aquarium.clean=100;}else return toast('Unknown code.');toast('Code accepted.');}}queueSave();render();}
function settingsPanel(){showSheet('Settings',`<div class="stack"><label class="pixel-panel">Difficulty <select id="difficulty"><option>relaxed</option><option>normal</option><option>challenge</option><option>sandbox</option></select></label><label class="pixel-panel"><input id="soundSetting" type="checkbox" ${state.settings.sound?'checked':''}> Sound effects</label><label class="pixel-panel"><input id="motionSetting" type="checkbox" ${state.settings.reducedMotion?'checked':''}> Reduced motion</label><div class="pixel-grid">${actionButton('Export Save','Download JSON backup','settings:export')}${actionButton('Import Save','Restore JSON backup','settings:import')}${actionButton('New Egg','Archive and restart','settings:egg')}${actionButton('FULL RESET','Erase save and music','settings:reset')}</div></div>`,'SETTINGS');$('#difficulty').value=state.settings.difficulty;$('#difficulty').onchange=e=>{state.settings.difficulty=e.target.value;queueSave();};$('#soundSetting').onchange=e=>{state.settings.sound=e.target.checked;queueSave();};$('#motionSetting').onchange=e=>{state.settings.reducedMotion=e.target.checked;queueSave();};}
async function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tamachibi-save-gen${state.pet.generation}.json`;a.click();URL.revokeObjectURL(a.href);}
async function importSaveFile(file){const parsed=JSON.parse(await file.text());state=parsed;normalize();await save();location.reload();}
async function fullReset(){if(!confirm('Erase the complete game and imported music?'))return;await idbClear('tracks');await idbDelete('kv','state');location.reload();}
function newEgg(){if(!confirm('Archive the current Tamagotchi and begin a new egg?'))return;archivePet();const album=state.pet.album,generation=state.pet.generation+1;state.pet={...baseState().pet,album,generation};ui.eggChoices=makeEggChoices();ui.eggIndex=0;ui.screen='eggSelect';closeSheet();queueSave();render();}

// ---------- games ----------
const GAME_KINDS=['catch','rps','guess','blocks','mines','shuffle','memory','sprint','breaker','meteor','jump','sort','match'];
function gamesPanel(){if(state.pet.stage==='egg')return toast('Games begin after hatch.');const stage=state.pet.stage;showSheet('Games',`<div class="pixel-panel"><h3>Arcade</h3><div class="pixel-grid">${DATA.arcadeGames.map((n,i)=>actionButton(n,`Played ${state.gameCounts[n]||0}`,`game:arcade:${i}`)).join('')}</div></div><div class="pixel-panel"><h3>${stage.toUpperCase()} GAMES</h3><div class="pixel-grid">${(DATA.lifeStageGames[stage]||[]).map((n,i)=>actionButton(n,'Schedule activity',`game:stage:${i}`)).join('')}</div></div>`,'PLAY');}
function startGame(kind,name){showSheet(name,`<canvas id="miniCanvas" class="game-canvas" width="128" height="64"></canvas><div class="row"><b id="gameScore">Score 0</b><span id="gameInfo">Ready</span></div><div class="game-controls"><button id="gameL">D0 LEFT</button><button id="gameS" class="primary">D1 ACT</button><button id="gameR">D2 RIGHT</button></div><button id="gameExit" class="danger" style="width:100%;margin-top:8px">END GAME</button>`,'MINIGAME');const c=$('#miniCanvas'),g=c.getContext('2d');g.imageSmoothingEnabled=false;game={kind,name,g,c,score:0,lives:3,started:performance.now(),duration:22000,player:60,objects:[],sequence:[],input:[],cursor:0,board:null,ball:{x:64,y:45,vx:1.4,vy:-1.3},active:true,last:performance.now(),round:0};if(kind==='memory'||kind==='match')newMemoryRound();if(kind==='mines')initMines();$('#gameL').onpointerdown=()=>gameInput('left');$('#gameS').onpointerdown=()=>gameInput('act');$('#gameR').onpointerdown=()=>gameInput('right');$('#gameExit').onclick=()=>finishGame(false);requestAnimationFrame(gameLoop);}
function newMemoryRound(){game.sequence=Array.from({length:3+Math.min(5,game.round)},()=>rand(2));game.input=[];game.showUntil=performance.now()+1800;game.round++;}
function initMines(){game.board=Array.from({length:5},()=>Array(5).fill(0));for(let i=0;i<5;i++){let x,y;do{x=rand(5);y=rand(5);}while(game.board[y][x]===9);game.board[y][x]=9;}game.revealed=Array.from({length:5},()=>Array(5).fill(false));game.cx=2;game.cy=2;}
function gameInput(a){if(!game||!game.active)return;if(a==='left')game.player-=8;if(a==='right')game.player+=8;game.player=clamp(game.player,4,124);if(game.kind==='rps'&&a!=='act'){game.choice=a==='left'?0:2;}if(game.kind==='guess'&&a!=='act'){game.choice=clamp((game.choice??5)+(a==='left'?-1:1),1,9);}if(game.kind==='memory'&&a!=='act'){game.input.push(a==='left'?0:1);if(game.input.length===game.sequence.length){if(game.input.every((v,i)=>v===game.sequence[i])){game.score+=2;newMemoryRound();}else{game.lives--;game.input=[];}}}if(game.kind==='mines'){if(a==='left')game.cx=(game.cx+4)%5;if(a==='right')game.cx=(game.cx+1)%5;if(a==='act'){if(game.board[game.cy][game.cx]===9){game.lives--;game.board[game.cy][game.cx]=0;}else{game.revealed[game.cy][game.cx]=true;game.score++;}game.cy=(game.cy+1)%5;}}if(game.kind==='sprint'&&a==='act')game.score++;if(game.kind==='timing'&&a==='act'){if(Math.abs(game.marker-64)<16)game.score+=2;else game.lives--;}if(game.kind==='sort'&&a!=='act'){const expected=game.sortType===0?'left':'right';if(a===expected)game.score++;else game.lives--;game.sortType=rand(2);}if(game.kind==='rps'&&a==='act'){const cpu=rand(3),pl=game.choice??1;if(pl===cpu)game.score++;else if((pl-cpu+3)%3===1)game.score+=2;else game.lives--;game.choice=null;}if(game.kind==='guess'&&a==='act'){const target=game.target??(game.target=1+rand(9)),ch=game.choice??5;if(ch===target){game.score+=3;game.target=1+rand(9);}else game.lives--;}}
function gameLoop(ts){if(!game||!game.active)return;const dt=Math.min(.05,(ts-game.last)/1000);game.last=ts;const g=game.g;g.fillStyle='#020303';g.fillRect(0,0,128,64);g.fillStyle='#f6f3df';g.strokeStyle='#f6f3df';g.font='7px monospace';const left=game.duration-(ts-game.started);if(left<=0||game.lives<=0){finishGame(true);return;}$('#gameScore').textContent=`Score ${game.score}`;$('#gameInfo').textContent=`${Math.ceil(left/1000)}s · ♥${game.lives}`;
 if(['catch','dodge','meteor','jump'].includes(game.kind)){if(Math.random()<dt*2.3)game.objects.push({x:rand(120)+4,y:0,vy:18+rand(18),good:game.kind!=='dodge'&&Math.random()>.25});for(const o of game.objects){o.y+=o.vy*dt;if(game.kind==='jump'){o.x-=18*dt;}g.fillRect(o.x,o.y,4,4);}g.fillRect(game.player-5,56,10,4);for(let i=game.objects.length-1;i>=0;i--){const o=game.objects[i];if(o.y>54&&Math.abs(o.x-game.player)<9){if(o.good)game.score++;else game.lives--;game.objects.splice(i,1);}else if(o.y>64)game.objects.splice(i,1);}}
 else if(game.kind==='timing'){game.marker=(Math.sin(ts/250)+1)*60+4;g.strokeRect(48,24,32,12);g.fillRect(game.marker,20,2,24);g.fillText('Press ACT in box',23,48);}
 else if(game.kind==='memory'||game.kind==='match'){g.fillText(ts<game.showUntil?game.sequence.map(v=>v?'R':'L').join(' '):'Repeat with D0/D2',18,24);g.fillText(`Round ${game.round}`,46,38);}
 else if(game.kind==='rps'){g.fillText('D0 ROCK  D1 GO  D2 PAPER',3,20);g.fillText(`Choice ${game.choice??'-'}`,42,35);}
 else if(game.kind==='guess'){g.fillText('Choose 1-9, then ACT',13,20);g.font='18px monospace';g.fillText(game.choice??5,56,34);}
 else if(game.kind==='mines'){for(let y=0;y<5;y++)for(let x=0;x<5;x++){const xx=37+x*11,yy=5+y*11;g.strokeRect(xx,yy,9,9);if(game.revealed[y][x])g.fillText('·',xx+3,yy+1);if(x===game.cx&&y===game.cy)g.strokeRect(xx-1,yy-1,11,11);}}
 else if(game.kind==='blocks'){if(Math.random()<dt*2){game.score++;}for(let i=0;i<10;i++)g.strokeRect(42+(i%5)*9,50-Math.floor(i/5)*9,8,8);g.fillText('Stack blocks',35,8);}
 else if(game.kind==='breaker'){const b=game.ball;b.x+=b.vx*35*dt;b.y+=b.vy*35*dt;if(b.x<3||b.x>125)b.vx*=-1;if(b.y<12)b.vy*=-1;if(b.y>55){if(Math.abs(b.x-game.player)<16){b.vy=-Math.abs(b.vy);game.score++;}else{game.lives--;b.x=64;b.y=35;}}for(let i=0;i<8;i++)g.fillRect(12+i*13,10,10,4);g.fillRect(game.player-12,57,24,3);g.fillRect(b.x,b.y,3,3);}
 else if(game.kind==='sprint'){g.fillText('Tap ACT fast!',35,18);g.fillRect(8,40,Math.min(112,game.score*3),7);}
 else if(game.kind==='sort'){game.sortType??=rand(2);g.beginPath();if(game.sortType===0)g.arc(64,25,8,0,Math.PI*2);else g.rect(56,17,16,16);g.stroke();g.fillText('D0 circle / D2 square',12,45);}
 g.fillText(game.name.slice(0,18),2,2);requestAnimationFrame(gameLoop);}
 function finishGame(reward=true){if(!game)return;game.active=false;const score=game.score,name=game.name;if(reward){state.gameCounts[name]=(state.gameCounts[name]||0)+1;state.pet.coins+=Math.max(1,Math.floor(score/2));addStat('happy',score>=5?2:1);addStat('energy',-1);if(name.toLowerCase().includes('study')||name.toLowerCase().includes('quiz'))addSkill('smart',1);else addSkill('fit',1);changeBond(1);if(score>=10)markAchievement(`${name} Star`);queueSave();toast(`Score ${score}`);}game=null;closeSheet();render();}
 function stopGame(reward=false){finishGame(reward);}

// ---------- music ----------
async function loadTracks(){tracks=await idbAll('tracks');}
function parseTrack(file){const base=file.name.replace(/\.mp3$/i,''),parts=base.split('_'),path=file.webkitRelativePath||'';let artist=parts.length>1?parts.shift():(path.includes('/')?path.split('/').slice(-2,-1)[0]:'Unknown Artist');return{id:crypto.randomUUID(),artist:artist.trim()||'Unknown Artist',title:parts.join('_').trim()||base,file,addedAt:now()};}
async function importTracks(files){for(const f of files)if(f.type==='audio/mpeg'||/\.mp3$/i.test(f.name))await idbPut('tracks',parseTrack(f));await loadTracks();toast(`${files.length} files processed.`);musicPanel();}
function musicPanel(filter='all'){let list=tracks;if(filter==='favorites')list=tracks.filter(t=>state.music.favorites.includes(t.id));if(filter==='recent')list=state.music.recent.map(id=>tracks.find(t=>t.id===id)).filter(Boolean);showSheet('Music Disc',`<div class="pixel-grid">${actionButton('All Songs',`${tracks.length} saved`,'music:list')}${actionButton('Artists','Browse by artist','music:artists')}${actionButton('Favorites',`${state.music.favorites.length} songs`,'music:favorites')}${actionButton('Recent',`${state.music.recent.length} songs`,'music:recent')}${actionButton('Import MP3','Choose files','music:import')}${actionButton('Import Folder','Artist folders','music:folder')}</div>${filter!=='all'?trackHTML(list):''}<div class="pixel-panel"><label>Volume <input id="musicVolume" type="range" min="0" max="1" step=".01" value="${state.music.volume}"></label></div>`,'MUSIC');const v=$('#musicVolume');if(v)v.oninput=e=>{state.music.volume=+e.target.value;audio.volume=state.music.volume;queueSave();};bindTrackRows();}
function trackHTML(list){return`<div class="pixel-panel">${list.map((t,i)=>`<div class="music-row"><div><strong>${t.title}</strong><small>${t.artist}</small></div><button data-track-id="${t.id}">PLAY</button></div>`).join('')||'<p>No songs in this list.</p>'}</div>`;}
function bindTrackRows(){$$('[data-track-id]').forEach(b=>b.onclick=()=>playTrackById(b.dataset.trackId));}
function allSongsPanel(){showSheet('All Songs',trackHTML(tracks),'MUSIC');bindTrackRows();}
function artistsPanel(){const arts=[...new Set(tracks.map(t=>t.artist))].sort();showSheet('Artists',arts.map(a=>`<button class="pixel-action" data-artist="${encodeURIComponent(a)}"><strong>${a}</strong><small>${tracks.filter(t=>t.artist===a).length} songs</small></button>`).join(''),'MUSIC');$$('[data-artist]').forEach(b=>b.onclick=()=>{const a=decodeURIComponent(b.dataset.artist);showSheet(a,trackHTML(tracks.filter(t=>t.artist===a)),'ARTIST');bindTrackRows();});}
async function playTrackById(id){const i=tracks.findIndex(t=>t.id===id);if(i<0)return;currentTrack=i;if(objectURL)URL.revokeObjectURL(objectURL);objectURL=URL.createObjectURL(tracks[i].file);audio.src=objectURL;audio.volume=state.music.volume;await audio.play();state.music.recent=[id,...state.music.recent.filter(x=>x!==id)].slice(0,12);setMediaSession(tracks[i]);closeSheet();ui.screen='scene';queueSave();render();}
function togglePlay(){if(currentTrack<0)return;if(audio.paused)audio.play();else audio.pause();render();}
function nextTrack(dir=1){if(!tracks.length)return;const i=(currentTrack+dir+tracks.length)%tracks.length;playTrackById(tracks[i].id);}
function toggleFavorite(){if(currentTrack<0)return;const id=tracks[currentTrack].id;state.music.favorites=state.music.favorites.includes(id)?state.music.favorites.filter(x=>x!==id):[...state.music.favorites,id];queueSave();}
function setMediaSession(t){if(!('mediaSession'in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:'Tamachibi Music Disc'});navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',()=>nextTrack(-1));navigator.mediaSession.setActionHandler('nexttrack',()=>nextTrack(1));}

// ---------- input/menu dispatch ----------
function handleButton(n,long=false){beep(350+n*80,.025);if($('#dialogue').classList.contains('hidden')===false)return;if(!$('#sheet').classList.contains('hidden'))return;if(currentTrack>=0){if(long&&n===2){audio.pause();currentTrack=-1;musicPanel();return;}if(n===0)nextTrack(-1);else if(n===1)togglePlay();else nextTrack(1);return;}if(ui.screen==='eggSelect'){if(n===0)ui.eggIndex=(ui.eggIndex+3)%4;else if(n===2)ui.eggIndex=(ui.eggIndex+1)%4;else chooseEgg();render();return;}if(ui.screen==='menu'){if(long&&n===2){ui.screen='scene';render();return;}if(n===0)ui.menuIndex=(ui.menuIndex+MENU.length-1)%MENU.length;else if(n===2)ui.menuIndex=(ui.menuIndex+1)%MENU.length;else activateMenu();render();return;}if(ui.world===1){if(n===0)ui.roomIndex=(ui.roomIndex+DATA.rooms.length-1)%DATA.rooms.length;else if(n===2)ui.roomIndex=(ui.roomIndex+1)%DATA.rooms.length;else openRoom();}else if(ui.world===2){if(n===0)ui.cityIndex=(ui.cityIndex+DATA.city.length-1)%DATA.city.length;else if(n===2)ui.cityIndex=(ui.cityIndex+1)%DATA.city.length;else openCity();}else{if(n===1){ui.screen='menu';}else{ui.screen='menu';ui.menuIndex=(ui.menuIndex+(n===0?-1:1)+MENU.length)%MENU.length;}}render();}
function activateMenu(){const item=MENU[ui.menuIndex];if(!itemUnlocked(item))return toast(state.pet.stage==='egg'?'Unlocks after hatch.':'Not available at this age.');const a=item[2];if(a==='food')feedPanel();else if(a==='games')gamesPanel();else if(a==='clean')cleanAction();else if(a==='medicine')medicinePanel();else if(a==='talk')talkPanel();else if(a==='love')loveAction();else if(a==='walk'||a==='train'||a==='study'){startGame(a==='study'?'memory':a==='train'?'sprint':'dodge',item[0]);}else if(a==='garden')gardenPanel(false);else if(a==='plants')gardenPanel(true);else if(a==='aquarium')aquariumPanel();else if(a==='music')musicPanel();else if(a==='stats')statsPanel();else if(a==='shop')shopPanel();else if(a==='explore')startGame('dodge','Exploration');else if(a==='cook')cookPanel();else if(a==='job')careerPanel();else if(a==='room')roomPanel();else if(a==='family')familyPanel();else if(a==='album')collectionsPanel();else if(a==='life')livingPanel();else if(a==='paradise')paradisePanel();else settingsPanel();}
function roomPanel(){showSheet('Room & Decor',`<div class="pixel-panel"><p>Current room theme ${state.pet.roomStyle} · Hat ${state.pet.outfit}</p></div><div class="pixel-grid">${state.inventory.hats.map(i=>actionButton(DATA.outfits[i]||`Hat ${i}`,'Wear this hat',`wear:${i}`)).join('')}${state.inventory.rooms.map(i=>actionButton(`Room Theme ${i}`,'Use this room',`room:${i}`)).join('')}</div>`,'DECOR');}
function openRoom(){const r=DATA.rooms[ui.roomIndex];if(r==='Kitchen')cookPanel();else if(r==='Garden')gardenPanel(false);else if(r==='Plant Room')gardenPanel(true);else if(r==='Aquarium')aquariumPanel();else if(r==='Family Room')familyPanel();else roomPanel();}
function openCity(){const p=DATA.city[ui.cityIndex];if(p==='Neighbors')neighborPanel();else if(p==='Market')shopPanel();else if(p==='Clinic')medicinePanel();else if(p==='School / Work')state.pet.stage==='adult'?careerPanel():statsPanel();else if(p==='Museum')collectionsPanel();else if(p==='Spaceport')paradisePanel();else startGame(p==='Park'?'catch':'timing',p);}
function handleAction(id){const[a,b,c]=id.split(':');if(a==='feed')feed(+b);else if(a==='medicine')medicine(b);else if(a==='talk'){if(b==='parent')parentTalk();else if(b==='growing')growingTalk();else if(b==='event')lifeEvent();else memoriesPanel();}else if(a==='aquarium')aquariumAction(b);else if(a==='family')familyAction(b);else if(a==='career')chooseCareer(+b);else if(a==='shop')shopAction(b);else if(a==='paradise')paradiseAction(b);else if(a==='life'){if(b==='journal')journalPanel();else goalsPanel();}else if(a==='settings'){if(b==='export')exportSave();else if(b==='import')$('#importSave').click();else if(b==='egg')newEgg();else fullReset();}else if(a==='game'){const list=b==='arcade'?DATA.arcadeGames:DATA.lifeStageGames[state.pet.stage],name=list[+c],kind=b==='arcade'?GAME_KINDS[+c%GAME_KINDS.length]:['catch','dodge','timing','memory','sort'][+c%5];startGame(kind,name);}else if(a==='music'){if(b==='list')allSongsPanel();else if(b==='artists')artistsPanel();else if(b==='favorites')musicPanel('favorites');else if(b==='recent')musicPanel('recent');else if(b==='import')$('#musicFiles').click();else $('#musicFolder').click();}else if(a==='wear'){state.pet.outfit=+b;queueSave();roomPanel();render();}else if(a==='room'){state.pet.roomStyle=+b;queueSave();roomPanel();render();}}

function beep(freq=440,d=.04){if(!state?.settings?.sound)return;try{audioCtx??=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d);}catch{}}
function urgentMessage(){const p=state.pet,act=currentActivity();if(act!=='home')return null;if(p.sick||p.stats.health<=2)return`${p.name} needs medicine.`;if(p.poop>=2||p.stats.clean<=2)return`${p.name} needs cleaning.`;if(p.stats.full<=2)return`${p.name} is very hungry.`;if(p.stats.energy<=2)return`${p.name} is exhausted.`;if(p.stats.happy<=2)return`${p.name} feels lonely.`;if(state.garden.plots.some(x=>x&&x.water<15))return'The garden needs water.';if(state.aquarium.fish.length&&state.aquarium.clean<25)return'The aquarium needs cleaning.';return null;}
async function checkCareNotification(){const msg=urgentMessage();if(!msg||!state.settings.notifications||Notification.permission!=='granted'||now()-state.notifications.lastShown<45*60000)return;state.notifications.lastShown=now();const reg=await navigator.serviceWorker?.ready;reg?.showNotification('Pico Tamachibi needs you',{body:msg,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:'tamachibi-care',renotify:true,data:{url:'./'}});queueSave();}

function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action);});$('#sheetClose').onclick=closeSheet;$('#dialogueContinue').onclick=()=>$('#dialogue').classList.add('hidden');$('#menuShortcut').onclick=()=>{ui.screen='menu';render();};$('#talkShortcut').onclick=talkPanel;$('#musicShortcut').onclick=musicPanel;$('#saveShortcut').onclick=async()=>{await save();toast('Game saved.');};$('#worldSlider').oninput=e=>{if(currentTrack>=0){state.music.volume=+e.target.value/100;audio.volume=state.music.volume;queueSave();drawStatus();return;}ui.world=+e.target.value;ui.screen='scene';render();queueSave();};
 const buttons=[['#btnLeft',0],['#btnSelect',1],['#btnRight',2]];for(const[sel,n]of buttons){const el=$(sel);el.addEventListener('pointerdown',()=>{holdTriggered=false;el.classList.add('pressed');holdTimer=setTimeout(()=>{holdTriggered=true;handleButton(n,true);},800)});const up=()=>{clearTimeout(holdTimer);el.classList.remove('pressed');if(!holdTriggered)handleButton(n,false)};el.addEventListener('pointerup',up);el.addEventListener('pointercancel',()=>{clearTimeout(holdTimer);el.classList.remove('pressed')});}
 $('#musicFiles').onchange=e=>importTracks([...e.target.files]);$('#musicFolder').onchange=e=>importTracks([...e.target.files]);$('#importSave').onchange=e=>e.target.files[0]&&importSaveFile(e.target.files[0]);$('#notifyBtn').onclick=async()=>{const p=await Notification.requestPermission();state.settings.notifications=p==='granted';queueSave();toast(p==='granted'?'Notifications enabled.':'Notifications not enabled.');};$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden');}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden');});window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else{applyOffline();render();}});audio.onended=()=>nextTrack(1);}
async function registerSW(){if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js');try{if('periodicSync'in reg&&state.settings.notifications)await reg.periodicSync.register('tamachibi-care',{minInterval:15*60*1000});}catch{}return reg;}}
async function init(){await openDB();await load();applyOffline();await loadTracks();bind();await registerSW();try{await navigator.storage?.persist?.();}catch{}if(state.summary.length){const s=$('#offlineSummary');s.textContent=state.summary[0];s.classList.remove('hidden');}render();setInterval(tick,1000);setInterval(checkCareNotification,120000);}
init().catch(err=>{console.error(err);document.body.innerHTML=`<main style="padding:24px;color:white"><h1>Could not start Tamachibi</h1><pre>${err.stack||err}</pre></main>`;});
