
const CACHE='tamachibi-pwa-v1';
const ASSETS=['./','./index.html','./styles.css','./app.js','./data.js','./manifest.webmanifest','./icons/icon-192.png','./icons/icon-512.png','./icons/maskable-512.png'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(caches.match(e.request).then(cached=>cached||fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r;}).catch(()=>caches.match('./index.html'))));});
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('pico-tamachibi-pwa',3);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function getState(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('kv').objectStore('kv').get('state');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function putState(s){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('kv','readwrite').objectStore('kv').put(s,'state');r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function activity(state,d=new Date()){const stage=state.pet.stage,s={baby:{bed:19,wake:7},child:{bed:20,wake:7,school:[8,15]},teen:{bed:22,wake:7,school:[8,15]},adult:{bed:23,wake:6,work:[9,17]},elder:{bed:21,wake:6}}[stage],h=d.getHours()+d.getMinutes()/60,w=[0,6].includes(d.getDay());if(h>=s.bed||h<s.wake)return'sleep';if(!w&&s.school&&h>=s.school[0]&&h<s.school[1])return'school';if(!w&&s.work&&state.pet.career&&h>=s.work[0]&&h<s.work[1])return'work';return'home';}
function urgent(s){if(!s?.settings?.notifications||activity(s)!=='home')return null;const p=s.pet;if(p.sick||p.needs.health<20)return`${p.name} needs medical care.`;if(p.poop>=2||p.needs.clean<15)return`${p.name} needs cleaning.`;if(p.needs.food<15)return`${p.name} is very hungry.`;if(p.needs.energy<15)return`${p.name} is exhausted.`;if(p.needs.fun<15)return`${p.name} feels lonely.`;if(s.garden?.plots?.some(x=>x&&x.water<10))return'The garden needs water.';if(s.aquarium?.fish?.length&&s.aquarium.clean<20)return'The aquarium needs cleaning.';return null;}
async function notifyIfNeeded(){const s=await getState();const msg=urgent(s);if(!msg||Date.now()-(s.notifications?.lastShown||0)<45*60*1000)return;await self.registration.showNotification('Pico Tamachibi needs you',{body:msg,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:'tamachibi-care',renotify:true,data:{url:'./?open=care'}});s.notifications ||= {lastShown:0,log:[]};s.notifications.lastShown=Date.now();s.notifications.log=[{msg,at:Date.now()},...(s.notifications.log||[])].slice(0,30);await putState(s);}
self.addEventListener('periodicsync',e=>{if(e.tag==='tamachibi-care')e.waitUntil(notifyIfNeeded());});
self.addEventListener('sync',e=>{if(e.tag==='tamachibi-care')e.waitUntil(notifyIfNeeded());});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if('focus'in w){w.postMessage({type:'OPEN_PANEL',panel:'care'});return w.focus();}}return clients.openWindow(e.notification.data?.url||'./');}));});
