const CACHE='tamachibi-faithful-v2';
const ASSETS=['./','./index.html','./styles.css','./app.js','./data.js','./db.js','./manifest.webmanifest','./icons/icon-192.png','./icons/icon-512.png','./icons/maskable-512.png'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r;}).catch(()=>caches.match('./index.html'))));});
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('pico-tamachibi-faithful',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('kv'))d.createObjectStore('kv');if(!d.objectStoreNames.contains('tracks'))d.createObjectStore('tracks',{keyPath:'id',autoIncrement:true});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function readState(){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('kv').objectStore('kv').get('state');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function activity(s,d=new Date()){if(!s?.pet||s.pet.stage==='egg')return'home';const map={baby:{bed:19,wake:7},child:{bed:20,wake:7,school:[8,15]},teen:{bed:22,wake:7,school:[8,15]},adult:{bed:23,wake:6,work:[9,17]},elder:{bed:21,wake:6}},sc=map[s.pet.stage],h=d.getHours()+d.getMinutes()/60,w=[0,6].includes(d.getDay());if(h>=sc.bed||h<sc.wake)return'sleep';if(!w&&sc.school&&h>=sc.school[0]&&h<sc.school[1])return'school';if(!w&&sc.work&&s.pet.career&&h>=sc.work[0]&&h<sc.work[1])return'work';return'home';}
function urgent(s){if(!s?.settings?.notifications||activity(s)!=='home')return null;const p=s.pet;if(p.sick||p.stats.health<=2)return`${p.name} needs medicine.`;if(p.poop>=2||p.stats.clean<=2)return`${p.name} needs cleaning.`;if(p.stats.full<=2)return`${p.name} is hungry.`;if(p.stats.energy<=2)return`${p.name} is exhausted.`;if(p.stats.happy<=2)return`${p.name} wants attention.`;if(s.garden?.plots?.some(x=>x&&x.water<15))return'The garden needs water.';if(s.aquarium?.fish?.length&&s.aquarium.clean<25)return'The aquarium needs cleaning.';return null;}
async function notify(){const s=await readState(),msg=urgent(s);if(!msg||Date.now()-(s.notifications?.lastShown||0)<45*60000)return;await self.registration.showNotification('Pico Tamachibi needs you',{body:msg,icon:'icons/icon-192.png',badge:'icons/icon-192.png',tag:'tamachibi-care',renotify:true,data:{url:'./'}});}
self.addEventListener('periodicsync',e=>{if(e.tag==='tamachibi-care')e.waitUntil(notify());});
self.addEventListener('sync',e=>{if(e.tag==='tamachibi-care')e.waitUntil(notify());});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws)if('focus'in w)return w.focus();return clients.openWindow(e.notification.data?.url||'./');}));});
